id: 4
title: Sicurezza
icon: mdi:shield-home
panel: true
cards:

  - type: custom:layout-card
    layout: vertical
    cards:

      # Column 1

      - type: alarm-panel
        entity: alarm_control_panel.main

      - break

      # Column 2

      - type: picture-glance
        title: 'Porta: Entrata'
        entities:
          - binary_sensor.living_door_motion
          - binary_sensor.living_main_motion
          - binary_sensor.door_main
        camera_image: camera.living_door

  # TODO sensori di movimento
  # TODO ultima attivazione sensore porta
  # TODO ultimo trigger allarme
