path: security
title: Sicurezza
icon: mdi:shield-home
type: sections
max_columns: 2
sections:

  # Column 1
  - type: grid
    cards:

      - type: alarm-panel
        entity: alarm_control_panel.main

  # Column 2
  - type: grid
    cards:

      - type: picture-glance
        title: 'Porta: Entrata'
        entities:
          - binary_sensor.motion_living_door
          - binary_sensor.living_main_motion
          - binary_sensor.living_entrance_motion
          - binary_sensor.door_main
        camera_image: camera.living_door

# TODO sensori di movimento
# TODO ultima attivazione sensore porta
# TODO ultimo trigger allarme
