homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation_home
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret timezone_home
  auth_mfa_modules:
    - type: totp
  external_url: !secret app_url
  internal_url: !secret app_internal_url
  packages: !include_dir_named packages

# Enables logging
logger:
  default: info
  logs:
    # info stampa troppo
    homeassistant.components.mikrotik.hub: warning

# Show links to resources in log and frontend
#introduction:

# Enables API
api:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Enables mobile support
mobile_app:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  server_host: 127.0.0.1

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Community store
hacs:
  token: !secret github_token
  sidepanel_icon: 'mdi:package-variant'
  experimental: true

# Discover some devices automatically
#discovery:
#  enable:
#    - dlna_dmr

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
intent:

zeroconf:
  default_interface: false

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Recording only what is necessary
recorder:
  db_url: mysql+pymysql://homeassistant@localhost/homeassistant?charset=utf8
  include:
    entities:
      - input_select.house_mode
      - person.daniele
      - climate.boiler_main
      - sensor.battery_scatola
      - sensor.controlcenter_battery_level
      - sensor.daniele_payton_battery_level
      - sensor.battery_env_bedroom
      - sensor.battery_env_external
      - sensor.battery_env_living
      - sensor.battery_door_main
      - sensor.battery_motion_living
      - sensor.battery_motion_bedroom
      - sensor.battery_motion_entrance
      - sensor.homeserver_cpu_used
      - sensor.homeserver_ram_used_percent
      - sensor.cputemp_scatola
      - sensor.processor_use
      - sensor.memory_use_percent
      - sensor.temperature_external
      - sensor.humidity_external
      - sensor.weather_temperature
      - sensor.weather_apparent_temperature
      - sensor.homeserver_w83627thf_1_temperature
      - sensor.temperature_bedroom
      - sensor.pressure_bedroom
      - sensor.humidity_bedroom
      - sensor.temperature_living
      - sensor.pressure_living
      - sensor.humidity_living
      - sensor.temperature_kitchen
      - sensor.gas_concentration_kitchen
      - binary_sensor.water_bathroom1
      - sensor.battery_water_bathroom1
      - sensor.battery_env_bathroom1
      - sensor.humidity_bathroom1
      - sensor.temperature_bathroom1
      - sensor.temperature_average
      - sensor.humidity_average
      - sensor.hddtemp_homeserver_dev_disk_by_id_ata_wdc_wd1002faex_00z3a0_wd_wcatr9149732
      - sensor.hddtemp_homeserver_dev_disk_by_id_ata_wdc_wd1002faex_00z3a0_wd_wcatr9159143
      - sensor.mediarasp_cpu_used
      - sensor.mediarasp_cpu_thermal_1_temperature
      - device_tracker.thermostat
      - device_tracker.controlcenter
      # TEST presence >>>
      - device_tracker.daniele_paytonwifi
      - device_tracker.daniele_paytonble
      # <<< TEST
      - binary_sensor.motion_living_door
      - binary_sensor.living_main_motion
      - binary_sensor.living_entrance_motion
      - sensor.living_main_lux
      - sensor.bedroom_lux

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: amazon_polly
    voice: Bianca
    region_name: eu-west-3
    text_type: ssml
    aws_access_key_id: !secret aws_tts_access_key_id
    aws_secret_access_key: !secret aws_tts_secret_access_key
  - platform: microsoft
    api_key: !secret azure_tts_api_key
    language: 'it-it'
    gender: Female
    type: IsabellaNeural
    region: westeurope

mqtt:
  broker: localhost
  discovery: true

# Strumenti di notifica
notify:
  - name: everything
    platform: group
    services:
      - service: kodi
      - service: kontalk_daniele
  - platform: kodi
    name: kodi
    host: rasp
  - platform: xmpp
    name: kontalk_daniele
    sender: !secret xmpp_username
    password: !secret xmpp_password
    recipient: !secret xmpp_recipient_daniele

zha:
  database_path: /home/homeassistant/.homeassistant/zigbee.db

system_health:
wake_on_lan:

panel_iframe:
  thermostat:
    title: Termostato
    icon: mdi:thermometer-lines
    url: !secret thermostat_local_url

lovelace_gen:

lovelace:
  mode: yaml
  resources:
    # tracked
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/travel-time-card/travel-time-card.js
      type: js
    - url: /hacsfiles/text-divider-row/text-divider-row.js
      type: module
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: js
    - url: /hacsfiles/circle-sensor-card/circle-sensor-card.js
      type: module
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: js
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: js
    - url: /hacsfiles/weather-card/weather-card.js
      type: module
    - url: /hacsfiles/list-card/list-card.js
      type: js
    - url: /hacsfiles/search-card/search-card.js
      type: module
    - url: /hacsfiles/lovelace-paper-buttons-row/paper-buttons-row.js
      type: module
    # untracked
    - url: /local/ui/custom_ui/moment-with-locales.js?v=2.24.0
      type: js
    - url: /local/ui/custom_ui/thermostat-card.js?v=1
      type: module
    # Customizzata!! NON AGGIORNARE!
    - url: /local/ui/custom_ui/clock-card.js?track=false&v=1
      type: module
