
TTS_SAY_EVENT = 'HERMES_TTS_SAY'
TTS_SAY_FINISHED_EVENT = 'HERMES_TTS_SAY_FINISHED'

DIALOGUE_SESSION_STARTED_EVENT = 'HERMES_DIALOGUE_SESSION_STARTED'
DIALOGUE_SESSION_ENDED_EVENT = 'HERMES_DIALOGUE_SESSION_ENDED'

INTENT_EVENT = 'HERMES_INTENT'
