timer:
  # Timer attivato vocalmente
  spoken:
    name: Timer
    icon: mdi:timer

intent_script:

  # TODO SetCountdownAlarm:
  # TODO GetCountdownAlarm:
  # TODO ClearCountdownAlarm:

automation:

  - alias: TimerFinished
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.spoken
    action:
      - condition: state
        entity_id: timer.spoken
        state: idle
      - service: media_player.volume_set
        data:
          entity_id: media_player.lounge
          volume_level: !secret lounge_volume
      - service: media_player.play_media
        data:
          entity_id: media_player.lounge
          media_content_id: !secret alarm_media_url
          media_content_type: music
