
automation:

# FIXME queste automazioni andrebbero legate a sessionStarted/sessionEnded

  - alias: wakeword_disable
    trigger:
      # Kodi: in playing
      - trigger: state
        entity_id: 'media_player.kodi'
        to: 'playing'
      # TV che parla
      - trigger: template
        value_template: "{{ is_state_attr('media_player.tv', 'is_volume_muted', false) }}"
      # Internet non disponibile
      - trigger: state
        entity_id: binary_sensor.internet
        to: 'off'
    action:
      - action: rest_command.wakeword_disable

  - alias: wakeword_enable
    trigger:
      # Kodi: qualsiasi stato che non sia playing
      - trigger: state
        entity_id: 'media_player.kodi'
        from: 'playing'
      # TV spenta
      - trigger: state
        entity_id: 'media_player.tv'
        to: 'off'
      # TV muta
      - trigger: template
        value_template: "{{ is_state_attr('media_player.tv', 'is_volume_muted', true) }}"
    condition:
      - condition: and
        conditions:
          # Internet disponibile
          - condition: state
            entity_id: binary_sensor.internet
            state: 'on'
    action:
      - action: rest_command.wakeword_enable

  - alias: wakeword_enable2
    trigger:
      # Internet disponibile
      - trigger: state
        entity_id: binary_sensor.internet
        to: 'on'
    condition:
      condition: and
      conditions:
        # Kodi: qualsiasi stato che non sia playing
        - condition: template
          value_template: "{{ not is_state('media_player.kodi', 'playing') }}"
    action:
      - action: rest_command.wakeword_enable

rest_command:

  wakeword_enable:
    url: 'http://localhost:12101/api/listen-for-wake'
    method: post
    payload: 'on'

  wakeword_disable:
    url: 'http://localhost:12101/api/listen-for-wake'
    method: post
    payload: 'off'

random_template:
  templates_path: /home/homeassistant/.homeassistant/custom_templates
  language: it
