
automation:

# FIXME queste automazioni andrebbero legate a sessionStarted/sessionEnded

  - alias: wakeword_disable
    id: 78992390-3020-41ac-8f6c-29a4e7616b58
    trigger:
      # cinema mode
      - trigger: state
        entity_id: binary_sensor.cinema_mode
        to: 'on'
      # TV che parla
      - trigger: template
        value_template: "{{ is_state_attr('media_player.tv', 'is_volume_muted', false) }}"
      # Internet non disponibile
      - trigger: state
        entity_id: binary_sensor.internet
        to: 'off'
    condition:
      - condition: or
        conditions:
          # cinema mode
          - condition: state
            entity_id: binary_sensor.cinema_mode
            state: 'on'
          # Internet non disponibile
          - condition: state
            entity_id: binary_sensor.internet
            state: 'off'
    action:
      - action: switch.turn_on
        target:
          entity_id: switch.voice_living_mute

  - alias: wakeword_enable
    id: 1eba6369-b74b-429a-9d2f-84f41e597ecd
    trigger:
      # fuori da cinema mode
      - trigger: state
        entity_id: binary_sensor.cinema_mode
        to: 'off'
      # TV spenta
      - trigger: state
        entity_id: 'media_player.tv'
        to: 'off'
      # TV muta
      - trigger: template
        value_template: "{{ is_state_attr('media_player.tv', 'is_volume_muted', true) }}"
    condition:
      - condition: and
        conditions:
          # Internet disponibile
          - condition: state
            entity_id: binary_sensor.internet
            state: 'on'
    action:
      - action: switch.turn_off
        target:
          entity_id: switch.voice_living_mute

  - alias: wakeword_enable2
    id: 65c90d46-c5a2-46c6-9aa5-9f1179fe6b76
    trigger:
      # Internet disponibile
      - trigger: state
        entity_id: binary_sensor.internet
        to: 'on'
    condition:
      condition: and
      conditions:
        # fuori da cinema mode
        - condition: state
          entity_id: binary_sensor.cinema_mode
          state: 'off'
    action:
      - action: switch.turn_off
        target:
          entity_id: switch.voice_living_mute

  - alias: assist_suspend_media
    id: 7719bcba-6701-11f0-be78-0800277ca3d8
    trigger:
      - trigger: state
        entity_id: assist_satellite.voice_living
        to: listening
    action:
      - action: script.suspend_media_for_assist

random_template:
  templates_path: /home/homeassistant/.homeassistant/custom_templates
  language: it
