homeassistant:
  customize:
    script.goodmorning:
      friendly_name: Buongiorno!
      icon: mdi:coffee

intent_script:

  TrashReminderMorning:
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.trash_reminder_morning
      - event: assistant_speak_tts
        event_data_template:
          template: TrashReminderMorning
          variables:
            when_raw: "{{ when }}"

  GreetingGoodMorning:
    action:
      - service: script.goodmorning

  GreetingGeneral:
    action:
      - event: assistant_speak_tts
        event_data:
          template: GreetingGeneral

  Thankyou:
    action:
      - event: assistant_speak_tts
        event_data:
          template: thankyou

  AnnounceGoingAway:
    action:
      - service: script.announce_going_away

  # Saluto della buonanotte
  GreetingGoodNight:
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.house_mode
          option: night
      - event: assistant_speak_tts
        event_data:
          template: goodnight

input_boolean:

  # TODO prevedere variabile per indicare il giorno del reminder
  trash_reminder_morning:
    name: 'Porta la spazzatura domattina'
    initial: off
    icon: mdi:recycle

automation:

  # Avvisa di viaggi duri al lavoro se in mattina feriale e c'è qualcuno in casa
  - alias: work_commute_hard
    trigger:
      - platform: numeric_state
        entity_id: sensor.commute_to_work
        above: 35
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.workmorning_sensor
          state: 'on'
        - condition: numeric_state
          entity_id: sensor.people_home_count
          above: '0'
    action:
      - event: assistant_speak_tts
        event_data:
          template: work_commute_hard

  - alias: karen_internet_unavailable
    trigger:
      - platform: state
        entity_id: device_tracker.internet
        from: 'home'
        to: 'not_home'
    condition:
      condition: numeric_state
      entity_id: sensor.people_home_count
      above: '0'
    action:
      - service: script.say_something_rendered
        data:
          url: !secret karen_internet_unavailable_url

  - alias: karen_internet_restored
    trigger:
      - platform: state
        entity_id: device_tracker.internet
        from: 'not_home'
        to: 'home'
    condition:
      condition: numeric_state
      entity_id: sensor.people_home_count
      above: '0'
    action:
      - service: script.say_something_rendered
        data:
          url: !secret karen_internet_restored_url

  # Avviso vocale chiamata in arrivo sul cellulare
  - alias: payton_phone_call_incoming
    trigger:
      - platform: template
        value_template: '{{ states.sensor.payton_phone_call_incoming_caller.state|length > 0 }}'
    condition:
      condition: and
      conditions:
        # Se non ci sono media in riproduzione in TV
        - condition: state
          entity_id: binary_sensor.cinema_mode
          state: 'off'
    action:
      - event: assistant_speak_tts
        event_data_template:
          template: incoming_phone_call
          variables:
            caller: "{{ states.sensor.payton_phone_call_incoming_caller.state }}"

  # Alterazioni di stato della casa

  - alias: house_mode_assistant_misc_day
    trigger:
      - platform: state
        entity_id: input_select.house_mode
        to: day_working
      - platform: state
        entity_id: input_select.house_mode
        to: day_not_working
    action:
      - service: automation.turn_on
        entity_id:
          - automation.work_commute_hard
          - automation.karen_internet_unavailable
          - automation.karen_internet_restored
          - automation.payton_phone_call_incoming

  - alias: house_mode_assistant_misc_quiet1
    trigger:
      - platform: state
        entity_id: input_select.house_mode
        to: night
      - platform: state
        entity_id: input_select.house_mode
        to: dnd
      - platform: state
        entity_id: input_select.house_mode
        to: away
      - platform: state
        entity_id: input_select.house_mode
        to: extended_away
    action:
      - service: automation.turn_off
        entity_id:
          - automation.work_commute_hard
          - automation.karen_internet_unavailable
          - automation.karen_internet_restored
          - automation.payton_phone_call_incoming

  - alias: house_mode_assistant_misc_quiet2
    trigger:
      - platform: state
        entity_id: input_select.house_mode
        to: guest
    action:
      - service: automation.turn_off
        entity_id:
          - automation.work_commute_hard
          - automation.karen_internet_unavailable
          - automation.karen_internet_restored

sensor:
  - name: payton_phone_call_incoming_caller
    platform: mqtt
    state_topic: homeassistant/payton/device/phone/state
    value_template: "{{ value_json.caller_name if value_json.state == 'ringing' else '' }}"

script:

  # Saluto del buongiorno
  goodmorning:
    sequence:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.house_mode
          option: "{{ 'day_working' if is_state('binary_sensor.workday_sensor', 'on') else 'day_not_working' }}"
      - event: assistant_speak_tts
        event_data:
          template: goodmorning
      - condition: template
        value_template: '{{ 4 <= now().hour < 10 }}'
      - delay:
          seconds: 10
      - wait_template: "{{ is_state('media_player.lounge', 'idle') or is_state('media_player.lounge', 'paused') }}"
        timeout: '00:01:00'
      - service: media_player.volume_set
        data:
          entity_id: media_player.lounge
          volume_level: !secret lounge_volume
      - service: media_player.play_media
        data_template:
          entity_id: media_player.lounge
          media_content_id: >-
            {% set hour = states('sensor.time').split(':')[0] %}
            https://cdn.rtl.it/RTLFM/on-demand/giornale-orario/go_{{ hour }}.mp3
          media_content_type: music

  # Bentornato a casa
  welcome_home:
    sequence:
      - event: assistant_speak_tts
        event_data:
          template: welcome_home
      - condition: template
        value_template: '{{ (now().hour == 20 and now().minute < 10) or (now().hour == 19 and now().minute > 50) }}'
      - delay:
          seconds: 5
      #- wait_template: "{{ is_state('media_player.lounge', 'idle') or is_state('media_player.lounge', 'paused') }}"
      #  timeout: '00:01:00'
      - service: script.tv_channel_favourite_news

  # Andando via
  # TODO da sistemare con altre informazioni
  # TODO sfruttare macro
  # TODO variazioni di testo
  announce_going_away:
    sequence:
      - event: assistant_speak_tts
        event_data:
          template: announce_going_away
      - service: input_boolean.turn_off
        entity_id: input_boolean.trash_reminder_morning
      - service: switch.turn_on
        entity_id: switch.homeserver
