
automation:

# FIXME queste automazioni andrebbero legate a sessionStarted/sessionEnded

  - alias: wakeword_disable
    trigger:
      # Kodi: in playing
      - platform: state
        entity_id: 'media_player.kodi'
        to: 'playing'
      # TV che parla
      - platform: template
        value_template: "{{ is_state_attr('media_player.tv', 'is_volume_muted', false) }}"
      # Internet non disponibile
      - platform: state
        entity_id: device_tracker.internet
        to: 'not_home'
    action:
      - service: rest_command.wakeword_disable

  - alias: wakeword_enable
    trigger:
      # Kodi: qualsiasi stato che non sia playing
      - platform: state
        entity_id: 'media_player.kodi'
        from: 'playing'
      # TV spenta
      - platform: state
        entity_id: 'media_player.tv'
        to: 'off'
      # TV muta
      - platform: template
        value_template: "{{ is_state_attr('media_player.tv', 'is_volume_muted', true) }}"
    condition:
      - condition: and
        conditions:
          # Internet disponibile
          - condition: state
            entity_id: device_tracker.internet
            state: 'home'
    action:
      - service: rest_command.wakeword_enable

  - alias: wakeword_enable2
    trigger:
      # Internet disponibile
      - platform: state
        entity_id: device_tracker.internet
        to: 'home'
    condition:
      condition: and
      conditions:
        # Kodi: qualsiasi stato che non sia playing
        - condition: template
          value_template: "{{ not is_state('media_player.kodi', 'playing') }}"
    action:
      - service: rest_command.wakeword_enable

rest_command:

  wakeword_enable:
    url: 'http://localhost:12101/api/listen-for-wake'
    method: post
    payload: 'on'

  wakeword_disable:
    url: 'http://localhost:12101/api/listen-for-wake'
    method: post
    payload: 'off'

rhasspy_events:
  events:
    - GetTime
    - GetDate
    - GreetingGoodMorning
    - GreetingGeneral
    - Thankyou
    - AnnounceGoingAway
    - GreetingGoodNight
    - GetExternalTemperature
    - SetDinnerEating
    - AllLightsOff
    - LivingUtilityLightOn
    - SetCountdownAlarm
    - GetCountdownAlarm
    - ClearCountdownAlarm
    - TrashReminderMorning
    - GuestModeOn
    - GuestModeOff
    - StartMusicPlaylist
