# ### Environment devices definitions

homeassistant:
  customize:
    sensor.temperature_living:
      icon: mdi:thermometer
      device_class: temperature
    sensor.temperature_average:
      icon: mdi:thermometer
      device_class: temperature
    sensor.humidity_average:
      icon: mdi:water-percent
      device_class: temperature
    sensor.temperature_living_window:
      device_class: temperature
    climate.boiler_main:
      friendly_name: Riscaldamento
    climate.living_ac:
      friendly_name: "A/C soggiorno"
    climate.bedroom_ac:
      friendly_name: "A/C camera"

group:
  hvac_all:
    name: "Sistemi HVAC"
    entities:
      - climate.boiler_main
      - climate.living_ac
      - climate.bedroom_ac

  # TODO in teoria dovrebbe includere anche i condizionatori, ma la cosa è complicata
  hvac_heat:
    name: "HVAC riscaldamento"
    entities:
      - climate.boiler_main

  hvac_cool:
    name: "HVAC raffrescamento"
    entities:
      - climate.living_ac
      - climate.bedroom_ac

  env_kitchen:
    name: "Ambiente: Cucina"
    entities:
      - sensor.temperature_kitchen
      - sensor.humidity_kitchen

  env_bedroom:
    name: "Ambiente: Camera"
    entities:
      - sensor.temperature_bedroom
      - sensor.humidity_bedroom
      - sensor.pressure_bedroom

  env_living:
    name: "Ambiente: Soggiorno"
    entities:
      - sensor.temperature_living
      - sensor.humidity_living

  env_bathroom1:
    name: "Ambiente: Bagno 1"
    entities:
      - sensor.temperature_bathroom1
      - sensor.humidity_bathroom1

  env_studio:
    name: "Ambiente: Studio"
    entities:
      - sensor.temperature_studio
      - sensor.humidity_studio

  env_external:
    name: "Ambiente: Esterno"
    entities:
      - sensor.temperature_external
      - sensor.humidity_external
      - sensor.pressure_external

sensor:
  - name: temperature_average
    platform: min_max
    type: mean
    round_digits: 1
    unique_id: 4c20a20c-4230-4262-a0a2-0c42306262e3
    entity_ids:
      - sensor.temperature_kitchen
      - sensor.temperature_bedroom
      - sensor.temperature_living
      - sensor.temperature_bathroom1
      - sensor.temperature_studio

  - name: humidity_average
    platform: min_max
    type: mean
    round_digits: 1
    unique_id: 5c5d4c9b-db1f-469d-9d4c-9bdb1fd69d41
    entity_ids:
      - sensor.humidity_kitchen
      - sensor.humidity_bedroom
      - sensor.humidity_living
      - sensor.humidity_bathroom1
      - sensor.humidity_studio

  - name: temperature_living
    platform: min_max
    type: mean
    round_digits: 1
    unique_id: 0fc2834e-e517-426c-8283-4ee517626c0c
    entity_ids:
      # FIXME can't be used in winter because it's placed above a radiator
      #- sensor.temperature_living_window
      - sensor.temperature_living_table

  - name: trend_humidity_env_bathroom1_shower
    platform: derivative
    source: sensor.humidity_bathroom1_shower
    time_window: "00:05:00"
    unit_time: min

  - name: lux_bedroom
    platform: min_max
    type: mean
    round_digits: 0
    unique_id: 066a5c03-0bdd-4272-aa5c-030bddf272a2
    entity_ids:
      - sensor.lux_bedroom_left

template:
  - sensor:
      - name: temperature_living_window
        state: "{{ states('sensor.daikinap53460_inside_temperature') }}"
        unit_of_measurement: '°C'
        icon: mdi:thermometer
        state_class: measurement

binary_sensor:
  - platform: trend
    sensors:
      trend_humidity_env_bathroom1_shower:
        entity_id: sensor.humidity_bathroom1_shower

mqtt:
  sensor:
    - name: gas_level_kitchen
      state_topic: shellies/gas-kitchen/sensor/gas

    - name: gas_concentration_kitchen
      state_topic: shellies/gas-kitchen/sensor/concentration
      unit_of_measurement: 'PPM'

automation:
  - alias: thermostat_sync_local_temperature
    id: 67c2d370-27cf-4730-82d3-7027cf873017
    description: 'Sincronizza la temperatura rilevata dal termostato principale'
    triggers:
      - trigger: state
        entity_id: climate.boiler_main
        from: unavailable
      # variazione della temperatura media dei sensori
      - trigger: state
        entity_id: sensor.temperature_average
      # variazione della temperatura rilevata dal termostato
      - trigger: state
        entity_id: climate.boiler_main
        attribute: current_temperature
      - trigger: homeassistant
        event: start
    conditions:
      not:
        - condition: state
          entity_id: sensor.temperature_average
          state: unavailable
    actions:
      - variables:
          tempcalc: >-
            {{ (states('sensor.temperature_average')|float(0)|round(1) -
            (state_attr('climate.boiler_main', 'current_temperature')|float(0) -
            states('number.bosch_rbsh_rth0_zb_eu_local_temperature_offset')|float(0)))|round(1) }}
      - if:
          - condition: template
            value_template: "{{ tempcalc != states('number.bosch_rbsh_rth0_zb_eu_local_temperature_offset')|float(0) }}"
        then:
          - action: number.set_value
            data:
              value: "{{ tempcalc }}"
            target:
              entity_id: number.bosch_rbsh_rth0_zb_eu_local_temperature_offset
    mode: queued
    max: 3

  - alias: thermostat_sync_external_temperature
    id: d6d94b8f-4a5d-4765-994b-8f4a5da765f6
    description: 'Sincronizza la temperatura esterna per il display del termostato principale'
    triggers:
      - trigger: state
        entity_id: climate.boiler_main
        from: unavailable
        alias: 'Termostato disponibile'
      - trigger: state
        entity_id: sensor.temperature_external
        alias: 'Variazione temperatura esterna'
      - trigger: homeassistant
        event: start
    conditions:
      not:
        - condition: state
          entity_id: sensor.temperature_external
          state: unavailable
    actions:
      - action: number.set_value
        data:
          # supported precision by the thermostat display
          value: "{{ states('sensor.temperature_external')|round(1) }}"
        target:
          entity_id: number.climate_boiler_outdoor_temperature
    mode: queued
    max: 3
