# Chores data

homeassistant:
  customize:
    sensor.chore_bedroom_floor_dust:
      repeat_days: 2

    sensor.chore_surfaces_dust:
      repeat_days: 5

    sensor.chore_water_closet_clean:
      repeat_days: 6

    sensor.chore_change_sheets:
      repeat_days: 25

    sensor.chore_balcony_clean:
      repeat_days: 60

    sensor.chore_living_floor_clean:
      repeat_days: 30

    sensor.chore_garage_clean:
      repeat_days: 365

input_datetime:

  chore_bedroom_floor_dust_last:
    name: Ultima spazzata camera
    icon: mdi:broom
    has_date: true

  chore_surfaces_dust_last:
    name: Ultima pulizia superfici
    icon: mdi:broom
    has_date: true

  chore_water_closet_clean_last:
    name: Ultima pulizia sanitari
    icon: mdi:broom
    has_date: true

  chore_change_sheets_last:
    name: Ultimo cambia lenzuola
    icon: mdi:broom
    has_date: true

  chore_balcony_clean_last:
    name: Ultimo pulizia balcone
    icon: mdi:broom
    has_date: true

  chore_living_floor_clean_last:
    name: Ultima pulizia pavimento salone
    icon: mdi:broom
    has_date: true

  chore_garage_clean_last:
    name: Ultima pulizia garage
    icon: mdi:broom
    has_date: true

sensor:

  # TODO use a custom integration for this

  - platform: template
    sensors:
      chore_bedroom_floor_dust:
        value_template: >-
          {% set delta = (strptime(states.input_datetime.chore_bedroom_floor_dust_last.state, '%Y-%m-%d').date() +
              timedelta(days=states.sensor.chore_bedroom_floor_dust.attributes.repeat_days)) - now().date() %}
          {{ delta.days }}
        attribute_templates:
          next: >-
            {{
              strptime(states.input_datetime.chore_bedroom_floor_dust_last.state, '%Y-%m-%d').date() +
              timedelta(days=states.sensor.chore_bedroom_floor_dust.attributes.repeat_days)
            }}
        friendly_name: Spazzare camera
        icon_template: mdi:broom
        unit_of_measurement: 'g'

      chore_surfaces_dust:
        value_template: >-
          {% set delta = (strptime(states.input_datetime.chore_surfaces_dust_last.state, '%Y-%m-%d').date() +
              timedelta(days=states.sensor.chore_surfaces_dust.attributes.repeat_days)) - now().date() %}
          {{ delta.days }}
        attribute_templates:
          next: >-
            {{
              strptime(states.input_datetime.chore_surfaces_dust_last.state, '%Y-%m-%d').date() +
              timedelta(days=states.sensor.chore_surfaces_dust.attributes.repeat_days)
            }}
        friendly_name: Superfici
        icon_template: mdi:broom
        unit_of_measurement: 'g'

      chore_water_closet_clean:
        value_template: >-
          {% set delta = (strptime(states.input_datetime.chore_water_closet_clean_last.state, '%Y-%m-%d').date() +
              timedelta(days=states.sensor.chore_water_closet_clean.attributes.repeat_days)) - now().date() %}
          {{ delta.days }}
        attribute_templates:
          next: >-
            {{
              strptime(states.input_datetime.chore_water_closet_clean_last.state, '%Y-%m-%d').date() +
              timedelta(days=states.sensor.chore_water_closet_clean.attributes.repeat_days)
            }}
        friendly_name: Sanitari
        icon_template: mdi:broom
        unit_of_measurement: 'g'

      chore_change_sheets:
        value_template: >-
          {% set delta = (strptime(states.input_datetime.chore_change_sheets_last.state, '%Y-%m-%d').date() +
              timedelta(days=states.sensor.chore_change_sheets.attributes.repeat_days)) - now().date() %}
          {{ delta.days }}
        attribute_templates:
          next: >-
            {{
              strptime(states.input_datetime.chore_change_sheets_last.state, '%Y-%m-%d').date() +
              timedelta(days=states.sensor.chore_change_sheets.attributes.repeat_days)
            }}
        friendly_name: Cambia lenzuola
        icon_template: mdi:broom
        unit_of_measurement: 'g'

      chore_balcony_clean:
        value_template: >-
          {% set delta = (strptime(states.input_datetime.chore_balcony_clean_last.state, '%Y-%m-%d').date() +
              timedelta(days=states.sensor.chore_balcony_clean.attributes.repeat_days)) - now().date() %}
          {{ delta.days }}
        attribute_templates:
          next: >-
            {{
              strptime(states.input_datetime.chore_balcony_clean_last.state, '%Y-%m-%d').date() +
              timedelta(days=states.sensor.chore_balcony_clean.attributes.repeat_days)
            }}
        friendly_name: Pulizia balcone
        icon_template: mdi:broom
        unit_of_measurement: 'g'

      chore_living_floor_clean:
        value_template: >-
          {% set delta = (strptime(states.input_datetime.chore_living_floor_clean_last.state, '%Y-%m-%d').date() +
              timedelta(days=states.sensor.chore_living_floor_clean.attributes.repeat_days)) - now().date() %}
          {{ delta.days }}
        attribute_templates:
          next: >-
            {{
              strptime(states.input_datetime.chore_living_floor_clean_last.state, '%Y-%m-%d').date() +
              timedelta(days=states.sensor.chore_living_floor_clean.attributes.repeat_days)
            }}
        friendly_name: Pavimento salone
        icon_template: mdi:broom
        unit_of_measurement: 'g'

      chore_garage_clean:
        value_template: >-
          {% set delta = (strptime(states.input_datetime.chore_garage_clean_last.state, '%Y-%m-%d').date() +
              timedelta(days=states.sensor.chore_garage_clean.attributes.repeat_days)) - now().date() %}
          {{ delta.days }}
        attribute_templates:
          next: >-
            {{
              strptime(states.input_datetime.chore_garage_clean_last.state, '%Y-%m-%d').date() +
              timedelta(days=states.sensor.chore_garage_clean.attributes.repeat_days)
            }}
        friendly_name: Pulizia garage
        icon_template: mdi:broom
        unit_of_measurement: 'g'
