# Devices monitoring and tracking

homeassistant:
  customize:
    device_tracker.daniele_paytonrouter:
      friendly_name: Payton (Router)

    device_tracker.daniele_paytonwifi:
      friendly_name: Payton (WiFi)

    device_tracker.daniele_paytongps:
      friendly_name: Payton (GPS)
      icon: mdi:cellphone

    device_tracker.daniele_paytonble:
      friendly_name: Payton (BLE)

    sensor.daniele_payton_battery_level:
      friendly_name: Telefono

    sensor.controlcenter_battery_level:
      friendly_name: Centro di controllo

    sensor.battery_water_bathroom1:
      friendly_name: 'Acqua: bagno'

    sensor.battery_env_external:
      friendly_name: 'Ambiente: Esterno'

    sensor.battery_env_living:
      friendly_name: 'Ambiente: Salone'

    sensor.battery_env_bathroom1:
      friendly_name: 'Ambiente: Bagno'

    sensor.battery_env_bedroom:
      friendly_name: 'Ambiente: Camera'

    sensor.battery_env_kitchen:
      friendly_name: 'Ambiente: Cucina'

    sensor.battery_door_main:
      friendly_name: 'Porta: Entrata'

    binary_sensor.door_main:
      friendly_name: 'Porta: Entrata'

    sensor.battery_motion_living:
      friendly_name: 'Movimento: Salone'

    sensor.battery_motion_bedroom:
      friendly_name: 'Movimento: Camera'

    sensor.battery_motion_entrance:
      friendly_name: 'Movimento: Ingresso'

    binary_sensor.living_main_motion:
      friendly_name: 'Movimento: Salone'

    binary_sensor.motion_living_door:
      friendly_name: 'Movimento: Entrata'

    binary_sensor.living_entrance_motion:
      friendly_name: 'Movimento: Ingresso'

    binary_sensor.water_bathroom1:
      friendly_name: 'Acqua: bagno'

    automation.control_center_low_battery:
      friendly_name: Centro di controllo scarico

    sensor.status_controlcenter:
      friendly_name: Centro di controllo

    sensor.status_thermostat:
      friendly_name: Termostato

    sensor.status_mediarasp:
      friendly_name: Media center

    sensor.low_batteries:
      friendly_name: Batterie scariche

device_tracker:
  - platform: mqtt
    devices:
      daniele_paytonble: 'homeassistant/monitor/rasp/payton/device_tracker'
    source_type: bluetooth

sensor:

  - platform: template
    sensors:
      # Device con batteria scarica
      low_batteries:
        value_template: >
          {%- set threshold = 10 -%}
          {%- set result = namespace(count=0) -%}
          {%- for item in states['sensor'] if ((item.entity_id.startswith('sensor.battery_') or item.entity_id == 'sensor.controlcenter_battery_level') and item.state not in ('unknown', 'unavailable') and item.state | int < threshold) -%}
          {%- set result.count = result.count + 1 -%}
          {%- endfor -%}
          {{ result.count }}
        attribute_templates:
          devices: >
            {%- set threshold = 10 -%}
            {%- set result = namespace(items=[]) -%}
            {%- for item in states['sensor'] if ((item.entity_id.startswith('sensor.battery_') or item.entity_id == 'sensor.controlcenter_battery_level') and item.state not in ('unknown', 'unavailable') and item.state | int < threshold) -%}
            {% set result.items = result.items + [item.entity_id] %}
            {%- endfor -%}
            {{ result.items }}

      # da usare in UI per rappresentare stato assente
      status_controlcenter:
        unit_of_measurement: "%"
        device_class: battery
        value_template: >-
          {% if is_state('device_tracker.controlcenter', 'home') %}
          {{ states.sensor.controlcenter_battery_level.state }}
          {% else %}
          0
          {% endif %}

      status_thermostat:
        unit_of_measurement: "%"
        device_class: battery
        value_template: >-
          {% if is_state('device_tracker.thermostat', 'home') %}
          100
          {% else %}
          0
          {% endif %}

      status_mediarasp:
        unit_of_measurement: "%"
        device_class: battery
        value_template: >-
          {% if is_state('device_tracker.rasp', 'home') %}
          100
          {% else %}
          0
          {% endif %}

binary_sensor:

  - name: motion_living_door
    platform: mqtt
    state_topic: homeassistant/camera/living_door/motion
    device_class: motion

  # Sensore idleness computer
  - platform: command_line
    name: activity_notebook_daniele
    # FIXME non so perché ma è necessario il tr...
    command: >-
      ping -W 1 -c 1 notebook > /dev/null 2>&1 && (
      idle=$(/usr/bin/ssh daniele@notebook 2>/dev/null | tr -d '\n\r'); [ "$idle" -lt 60000 ] && echo 1 || echo 0) ||
      echo 0
    payload_on: "1"
    payload_off: "0"

proximity:
  prox_home_daniele:
    devices:
      - device_tracker.daniele_paytongps
    tolerance: 50

camera:
  - platform: mjpeg
    name: living_door
    mjpeg_url: http://localhost:9995/

image_processing:
  - platform: deepstack_object
    ip_address: localhost
    port: 5000
    api_key: Mysecretkey
    # scan_interval: 30 # Optional, in seconds
    #save_file_folder: /config/www/
    save_timestamped_file: True
    source:
      - entity_id: camera.living_door
        name: deepstack_person_detector

shell_command:
  start_living_door_camera: sudo systemctl start motion.service
  stop_living_door_camera: sudo systemctl stop motion.service

automation:
  - alias: control_center_low_battery
    trigger:
      - platform: numeric_state
        entity_id: sensor.controlcenter_battery_level
        below: 10
    action:
      service: notify.kontalk_daniele
      data_template:
        title: ''
        message: |-
          Batteria del centro di controllo bassa: {{ states.sensor.controlcenter_battery_level.state_with_unit }}

  - alias: alert_low_batteries
    trigger:
      platform: numeric_state
      entity_id: sensor.low_batteries
      above: '0'
      # evita sensori che riportano microcambiamenti
      for: 02:00:00
    action:
      - service: persistent_notification.create
        data_template:
          title: Batterie scariche
          message: >
            {%- for item in states['sensor'] if item.entity_id in states.sensor.low_batteries.attributes.devices -%}
            - {{ item.attributes.friendly_name }} ({{ item.state }}%)
            {% endfor -%}
          notification_id: alert_low_batteries
      - service: notify.kontalk_daniele
        data_template:
          title: ''
          message: |-
            Batterie scariche:
            {% for item in states['sensor'] if item.entity_id in states.sensor.low_batteries.attributes.devices -%}
            - {{ item.attributes.friendly_name }} ({{ item.state }}%)
            {% endfor -%}

  - alias: alert_low_batteries_dismiss
    trigger:
      platform: numeric_state
      entity_id: sensor.low_batteries
      below: '1'
    action:
      - service: persistent_notification.dismiss
        data_template:
          notification_id: alert_low_batteries

alert:
  battery_discharging_scatola:
    name: Batteria scatola in scaricamento
    message: 'Batteria scatola in scaricamento: {{ states.sensor.battery_scatola.state_with_unit }}'
    done_message: 'Batteria scatola carica.'
    entity_id: binary_sensor.battery_discharging_scatola
    state: 'on'
    repeat: 5
    can_acknowledge: true
    notifiers:
      - kontalk_daniele

group:
  motion_living:
    name: Living room motion
    entities:
      - binary_sensor.motion_living_door
      - binary_sensor.living_main_motion
      - binary_sensor.living_entrance_motion

  motion_bedroom:
    name: Bedroom motion
    entities:
      - binary_sensor.motion_bedroom

  motion_not_bedroom:
    name: All motion but bedroom
    entities:
      - group.motion_living
