# Generic device definitions

homeassistant:
  customize:
    sensor.controlcenter_battery_level:
      friendly_name: Centro di controllo

    sensor.battery_water_bathroom1:
      friendly_name: 'Acqua: bagno'

    sensor.battery_env_external:
      friendly_name: 'Ambiente: Esterno'
      unit_of_measurement: '%'

    sensor.battery_env_living:
      friendly_name: 'Ambiente: Soggiorno'
      unit_of_measurement: '%'

    sensor.battery_env_bathroom1:
      friendly_name: 'Ambiente: Bagno'
      unit_of_measurement: '%'

    sensor.battery_env_bedroom:
      friendly_name: 'Ambiente: Camera'
      unit_of_measurement: '%'

    sensor.battery_env_kitchen:
      friendly_name: 'Ambiente: Cucina'
      unit_of_measurement: '%'

    sensor.battery_env_studio:
      friendly_name: 'Ambiente: Studio'
      unit_of_measurement: '%'

    sensor.battery_door_main:
      friendly_name: 'Porta: Entrata'

    binary_sensor.door_main:
      friendly_name: 'Porta: Entrata'

    sensor.battery_lux_living:
      friendly_name: 'Lux: Soggiorno'

    sensor.battery_motion_living:
      friendly_name: 'Movimento: Soggiorno'

    sensor.battery_motion_bedroom:
      friendly_name: 'Movimento: Camera'

    sensor.battery_motion_entrance:
      friendly_name: 'Movimento: Ingresso'

    sensor.battery_presence_mainbed:
      friendly_name: 'Presenza: letto'

    sensor.battery_button_dustbin:
      friendly_name: 'Pulsante: Pattumiera'

    binary_sensor.living_main_motion:
      friendly_name: 'Movimento: Soggiorno'

    binary_sensor.motion_living_door:
      friendly_name: 'Movimento: Entrata'

    binary_sensor.living_entrance_motion:
      friendly_name: 'Movimento: Ingresso'

    binary_sensor.presence_mainbed:
      friendly_name: 'Presenza: letto'

    binary_sensor.water_bathroom1:
      friendly_name: 'Acqua: bagno'

ble_monitor:
  bt_interface: '5C:F3:70:99:5B:83'
  discovery: false
  restore_state: true
  report_unknown: false
  #active_scan: true
  devices:
    - mac: '58:2D:34:3A:0E:84'
      name: 'env_living'
    - mac: 'A4:C1:38:BE:E3:99'
      name: 'env_bathroom1'
      # TODO remove this stuff - it's for stock firmware
      # Mi Token: cf9f60209fbbcb68389326f3
      encryption_key: 'c15d08be9f48421c27963829582b7105'
    - mac: 'A4:C1:38:CF:AE:8F'
      name: 'env_studio'
      # TODO remove this stuff - it's for stock firmware
      # Mi Token: 09e489852a835cae9f057a90
      encryption_key: 'c9ba2e2bf6877b235718edde1ecbeeaf'
    - mac: 'A4:C1:38:73:F0:E9'
      name: 'env_bedroom'
    - mac: '18:45:16:C5:EB:85'
      name: 'toothbrush'

mqtt:
  device_tracker:
  binary_sensor:
    - name: motion_living_door
      state_topic: homeassistant/camera/living_door/motion
      device_class: motion

image_processing:
  - platform: deepstack_object
    ip_address: localhost
    port: 5000
    api_key: Mysecretkey
    # scan_interval: 30 # Optional, in seconds
    #save_file_folder: /config/www/
    save_timestamped_file: True
    source:
      - entity_id: camera.living_door
        name: deepstack_person_detector

shell_command:
  start_living_door_camera: sudo systemctl start motion.service
  stop_living_door_camera: sudo systemctl stop motion.service

group:
  motion_living:
    name: Living room motion
    entities:
      # TODO da configurare
      #- binary_sensor.motion_living_door
      #- binary_sensor.living_main_motion
      - binary_sensor.living_entrance_motion

  motion_bedroom:
    name: Bedroom motion
    entities:
      - binary_sensor.motion_bedroom

  motion_not_bedroom:
    name: All motion but bedroom
    entities:
      - group.motion_living
