# ### Device presence and battery monitoring
# TODO allarmi per sensori che spariscono, data una lista di sensori noti

homeassistant:
  customize:
    sensor.low_batteries:
      friendly_name: Batterie scariche

    sensor.temperature_sensors_stuck:
      friendly_name: Sensori di temperatura bloccati

    sensor.lights_unavailable:
      friendly_name: Luci non disponibili

template:
  - sensor:
      # Device con batteria scarica
      # TODO use entities from battery-notes
      - name: low_batteries
        state: >
          {%- set threshold = 10 -%}
          {%- set result = namespace(count=0) -%}
          {%- for item in states['sensor'] if ((item.entity_id.startswith('sensor.battery_') or item.entity_id == 'sensor.controlcenter_battery_level') and item.state not in ('unknown', 'unavailable') and item.state | int < threshold) -%}
          {%- set result.count = result.count + 1 -%}
          {%- endfor -%}
          {{ result.count }}
        attributes:
          devices: >
            {%- set threshold = 10 -%}
            {%- set result = namespace(items=[]) -%}
            {%- for item in states['sensor'] if ((item.entity_id.startswith('sensor.battery_') or item.entity_id == 'sensor.controlcenter_battery_level') and item.state not in ('unknown', 'unavailable') and item.state | int < threshold) -%}
            {% set result.items = result.items + [item.entity_id] %}
            {%- endfor -%}
            {{ result.items }}

      # Sensori di temperatura bloccati
      - name: temperature_sensors_stuck
        state: >
          {%- set threshold = 24 -%}
          {%- set result = namespace(count=0) -%}
          {%- for item in states['sensor']
            if item.entity_id.startswith('sensor.temperature_') and item.state not in ('unknown', 'unavailable')
              and now() - item.last_changed >= timedelta (hours=threshold) -%}
          {%- set result.count = result.count + 1 -%}
          {%- endfor -%}
          {{ result.count }}
        attributes:
          devices: >
            {%- set threshold = 24 -%}
            {%- set result = namespace(items=[]) -%}
            {%- for item in states['sensor']
              if item.entity_id.startswith('sensor.temperature_') and item.state not in ('unknown', 'unavailable')
                and now() - item.last_changed >= timedelta (hours=threshold) -%}
            {% set result.items = result.items + [item.entity_id] %}
            {%- endfor -%}
            {{ result.items }}

      # Luci non disponibili
      - name: lights_unavailable
        state: >
          {%- set result = namespace(count=0) -%}
          {%- for item in states['light']
            if item.state in ('unknown', 'unavailable') -%}
          {%- set result.count = result.count + 1 -%}
          {%- endfor -%}
          {{ result.count }}
        attributes:
          devices: >
            {%- set result = namespace(items=[]) -%}
            {%- for item in states['light']
              if item.state in ('unknown', 'unavailable') -%}
            {% set result.items = result.items + [item.entity_id] %}
            {%- endfor -%}
            {{ result.items }}

      # da usare in UI per rappresentare stato assente
      - name: status_controlcenter
        unit_of_measurement: "%"
        device_class: battery
        state: >-
          {% if is_state('device_tracker.controlcenter', 'home') %}
          {{ states.sensor.controlcenter_battery_level.state }}
          {% else %}
          0
          {% endif %}

      - name: status_thermostat
        unit_of_measurement: "%"
        device_class: battery
        state: >-
          {% if not is_state('climate.boiler_main', 'unavailable') %}
          100
          {% else %}
          0
          {% endif %}

      - name: status_mediarasp
        unit_of_measurement: "%"
        device_class: battery
        state: >-
          {% if is_state('device_tracker.rasp', 'home') %}
          100
          {% else %}
          0
          {% endif %}

automation:
  - alias: control_center_low_battery
    id: a64c4dea-2c0d-11ef-9cb5-e7d9d5cb4346
    description: Notifica centro di controllo scarico
    trigger:
      - trigger: numeric_state
        entity_id: sensor.controlcenter_battery_level
        below: 10
    action:
      - action: script.notify_info
        data:
          category: Sistema
          message: |-
            Batteria del centro di controllo bassa: {{ states.sensor.controlcenter_battery_level.state_with_unit }}

  - alias: alert_low_batteries
    id: d60577fa-2c0d-11ef-b5c7-9ff802017551
    description: Notifica batterie scariche
    trigger:
      - trigger: event
        event_type: battery_notes_battery_threshold
        event_data:
          battery_low: true
        alias: Battery went low
    action:
      - action: persistent_notification.create
        data:
          title: "Batteria scarica: {{ trigger.event.data.device_name }}"
          message: >
            Batteria al {{
            trigger.event.data.battery_level }}% {{ '\n' -}} Sostituiscila con {{
            trigger.event.data.battery_quantity }}x {{
            trigger.event.data.battery_type }}
          notification_id: "{{ trigger.event.data.device_id }}-{{ trigger.event.data.source_entity_id }}"

  - alias: alert_low_batteries_dismiss
    id: e12b49a1-68a3-11f0-997a-0800277ca3d8
    trigger:
      - trigger: event
        event_type: battery_notes_battery_threshold
        event_data:
          battery_low: false
        alias: Battery went high
    action:
      - action: persistent_notification.dismiss
        data:
          notification_id: "{{ trigger.event.data.device_id }}-{{ trigger.event.data.source_entity_id }}"

  - alias: alert_temperature_sensors_stuck
    id: 8fc0c7f2-78b3-11ef-ade2-ffb2e6ef8276
    description: Notifica sensori di temperature bloccati
    trigger:
      trigger: numeric_state
      entity_id: sensor.temperature_sensors_stuck
      above: '0'
      # evita sensori che riportano microcambiamenti
      for: 02:00:00
    action:
      - action: persistent_notification.create
        data:
          title: Sensori bloccati
          message: >
            {%- for item in states['sensor'] if item.entity_id in states.sensor.temperature_sensors_stuck.attributes.devices -%}
            - {{ item.attributes.friendly_name }} ({{ item.state }}%)
            {% endfor -%}
          notification_id: alert_temperature_sensors_stuck
      - action: script.notify_info
        data:
          category: Sistema
          message: |-
            Sensori bloccati:
            {% for item in states['sensor'] if item.entity_id in states.sensor.temperature_sensors_stuck.attributes.devices -%}
            - {{ item.attributes.friendly_name }} ({{ item.state }}%)
            {% endfor -%}

  - alias: alert_temperature_sensors_stuck_dismiss
    id: 7a9ce2a7-e29d-4e29-8f6f-472da19e2577
    trigger:
      trigger: numeric_state
      entity_id: sensor.temperature_sensors_stuck
      below: '1'
    action:
      - action: persistent_notification.dismiss
        data:
          notification_id: alert_temperature_sensors_stuck

  - alias: alert_unavailable_entities
    id: 120778d2-8da6-11f0-99da-b4b686ed2aba
    description: Monitora entities degne di nota per stato unavailable
    triggers:
      trigger: state
      entity_id:
        - light.living_ceiling
        - light.living_extra
        - light.external
        - light.kitchen_main
        - light.bedroom_left
        - light.external_bedroom
        - light.external_living
        - light.bedroom_main
        - light.studio
        - light.dayway
        - light.bathroom2
        - light.nightway
        - light.bathroom1_main
        - light.living_stand
        - light.living_ceiling_real
        - light.bathroom1_mirror
        - light.living_main
        - sensor.power_light_bathroom1_main
        - sensor.power_light_bathroom1_mirror
        - sensor.power_power_light_living_main
        - sensor.power_light_bedroom_left
        - sensor.power_light_bedroom_main
        - sensor.power_light_dayway
        - sensor.power_washing_machine
        # unreliable device
        # - sensor.power_mains_total
        - sensor.power_datacenter
        - vacuum.spulicchiator
        - climate.bedroom_ac
        - climate.living_ac
        - climate.boiler_main
      to: unavailable
      for:
        minutes: 5
    actions:
      - action: persistent_notification.create
        data:
          title: Sensore non disponibile
          message: >
            Sensore "{{ trigger.to_state.name }}" ({{ trigger.to_state.entity_id }}) da stato "{{ trigger.from_state.state }}" a stato "{{ trigger.to_state.state }}"
          notification_id: alert_unavailable_entities

  - alias: alert_home_assistant_startup
    id: cfcc7e21-0ab4-42b9-9f91-3a57aa5ab5a3
    trigger:
      trigger: homeassistant
      event: start
    action:
      - action: script.notify_debug
        data:
          message: |-
            Home Assistant avviato

alert:
  battery_discharging_scatola:
    name: Batteria scatola in scaricamento
    message: 'Batteria scatola in scaricamento: {{ states.sensor.battery_scatola.state_with_unit }}'
    done_message: 'Batteria scatola carica.'
    entity_id: binary_sensor.battery_discharging_scatola
    state: 'on'
    repeat: 5
    can_acknowledge: true
    notifiers:
      - information
