# House environmental sensors

homeassistant:
  customize:
    sensor.temp_kitchen:
      friendly_name: Cucina

    sensor.temp_bedroom:
      friendly_name: Camera

    sensor.humidity_bedroom:
      friendly_name: Camera

    sensor.pressure_bedroom:
      friendly_name: Camera

    sensor.env_living_temperature:
      friendly_name: Salone

    sensor.env_living_humidity:
      friendly_name: Salone

    sensor.pressure_living:
      friendly_name: Salone

group:
  env_bedroom:
    name: "Ambiente: Camera"
    entities:
      - sensor.temp_bedroom
      - sensor.humidity_bedroom
      - sensor.pressure_bedroom

  env_living:
    name: "Ambiente: Salone"
    entities:
      - sensor.env_living_temperature
      - sensor.env_living_humidity

  env_external:
    name: "Ambiente: Esterno"
    entities:
      - sensor.temp_external
      - sensor.humidity_external
      - sensor.pressure_external

  climate:
    name: Climate
    icon: mdi:fire
    entities:
      - sensor.temp_kitchen
      - sensor.env_living_temperature
      - sensor.temp_bedroom
      - climate.home_boiler

sensor:
  # rilevato dal termostato
  - name: temp_kitchen
    platform: mqtt
    state_topic: homeassistant/thermorasp/sensor/temp_core/temperature
    unit_of_measurement: '°C'
    device_class: temperature
    value_template: "{{ float(value_json.value) }}"

  - name: temp_average
    platform: average
    entities:
      # la cucina non è affidabile - sensor.temp_kitchen
      - sensor.temp_bedroom
      - sensor.env_living_temperature

  - name: humidity_average
    platform: average
    entities:
      - sensor.humidity_bedroom
      - sensor.env_living_humidity

  - platform: mitemp_bt
    mac: '58:2D:34:3A:0E:84'
    name: env_living
    monitored_conditions:
      - temperature
      - humidity
      - battery
    median: 1
    adapter: hci1

binary_sensor:

  - platform: template
    sensors:
      # Bisogno di luce in soggiorno
      living_need_light:
        entity_id:
          - sun.sun
          - sensor.living_main_lux
        value_template: >-
          {{ states.sensor.living_main_lux.state|int < 10 or is_state('sun.sun', 'below_horizon') }}

automation:
  - alias: house_on_fire
    trigger:
      - platform: numeric_state
        entity_id: sensor.temp_kitchen
        above: 42
      - platform: numeric_state
        entity_id: sensor.temp_bedroom
        above: 40
      - platform: numeric_state
        entity_id: sensor.env_living_temperature
        above: 40
    action:
      service: notify.kontalk_daniele
      data_template:
        title: "Allarme"
        message: |-
          Temperatura ambiente eccessiva!
          Cucina: {{ states.sensor.temp_kitchen.state_with_unit }}
          Camera da letto: {{ states.sensor.temp_bedroom.state_with_unit }}
