# ### Firmware
# Inspired by https://github.com/JamesMcCarthy79/Home-Assistant-Config/tree/master/config/packages/firmware

# no update notification is triggered, so we need a dedicated notification
automation:
  - alias: Notifica aggiornamento HASS
    id: 2c0756bd-f9d9-47c2-9d2a-70eb7125391d
    trigger:
      - trigger: state
        entity_id: update.home_assistant
        from: 'off'
        to: 'on'
    action:
      - action: script.notify_debug
        data:
          message: "Home Assistant {{ states('sensor.latest_version') }} è stato rilasciato."

template:
  - update:
      - name: Home Assistant
        icon: mdi:home-assistant
        installed_version: "{{ states('sensor.current_version') }}"
        latest_version: "{{ states('sensor.latest_version') }}"
        # no way to automatically install, so no install section

shell_command:
  # in teoria la cwd di HA è la cartella della configurazione
  upgrade_configuration_scm: git pull --ff-only

script:

  hass_upgrade_config_and_restart:
    sequence:
      - action: shell_command.upgrade_configuration_scm
      - action: homeassistant.restart

  # TODO hass_update:
