homeassistant:
  customize:
    input_select.house_mode:
      friendly_name: Modalità casa
      icon: mdi:home-assistant

input_select:
  house_mode:
    options:
      # -- Stati a casa --
      # Lavorativo
      - day_working
      # Non lavorativo
      - day_not_working
      # Notte
      - night
      # Ospiti
      - guest
      # Non disturbare
      - dnd
      # -- Stati fuori casa --
      # Casa vuota
      - away
      # Casa vuota per più di X ore
      - extended_away

automation:
  # Only house-wide house mode automations here

  - alias: mode_select_night
    trigger:
      - platform: state
        entity_id: input_select.house_mode
        to: night
    action:
      - service: light.turn_off
        entity_id: all

  - alias: mode_select_away
    trigger:
      - platform: state
        entity_id: input_select.house_mode
        to: away
    action:
      - service: light.turn_off
        entity_id: all

  # Impostazione automatica modalità giorno al mattino (risveglio)
  - alias: mode_auto_day
    trigger:
      # Rilevato movimento in salone
      - platform: state
        entity_id: group.motion_living
        to: 'on'
    condition:
      condition: and
      conditions:
        # Entro una certa ora di "mattina"
        - condition: time
          after: '06:00:00'
          before: '16:00:00'
        # Eravamo in modalità notte
        - condition: state
          entity_id: input_select.house_mode
          state: night
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.house_mode
          option: "{{ 'day_working' if is_state('binary_sensor.workday_sensor', 'on') else 'day_not_working' }}"

  # Impostazione automatica modalità casa vuota lunga
  - alias: mode_auto_extended_away
    trigger:
      - platform: state
        entity_id: input_select.house_mode
        to: away
        for: !secret extended_away_period
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.house_mode
          option: extended_away

  # Per debug: notifica cambio house mode
  - alias: notify_mode_change
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.house_mode
    action:
      - service: notify.kontalk_daniele
        data_template:
          title: "Info"
          message: |-
            House mode: {{ states.input_select.house_mode.state }}
