# TODO potrebbe essere spostato in "utility"

homeassistant:
  customize:
    input_select.house_mode:
      friendly_name: Modalità casa
      icon: mdi:home-assistant
    script.house_mode_night:
      friendly_name: Night mode
      icon: mdi:weather-night

input_select:
  house_mode:
    options:
      # -- Stati a casa --
      # Lavorativo
      - day_working
      # Non lavorativo
      - day_not_working
      # Notte
      - night
      # Ospiti
      - guest
      # Non disturbare
      - dnd
      # -- Stati fuori casa --
      # Casa vuota
      - away
      # Casa vuota per più di X ore
      - extended_away

automation:
  # Only house-wide house mode automations here

  - alias: mode_select_night
    trigger:
      - trigger: state
        entity_id: input_select.house_mode
        to: night
    action:
      - action: light.turn_off
        entity_id: all

  - alias: mode_select_away
    trigger:
      - trigger: state
        entity_id: input_select.house_mode
        to: away
    action:
      - action: light.turn_off
        entity_id: all

  # Impostazione automatica modalità giorno al mattino (risveglio)
  - alias: mode_auto_day
    trigger:
      # Rilevato movimento fuori dalla camera da letto
      - trigger: state
        entity_id: group.motion_not_bedroom
        to: 'on'
      - trigger: state
        entity_id: media_player.music
        to: 'playing'
      - trigger: state
        entity_id: binary_sensor.daniele_shiba_music_active
        to: 'on'
      - trigger: state
        entity_id:
          - light.bathroom1_main
          - light.bathroom1_mirror
          - light.bathroom2
          - light.kitchen_main
        to: 'on'
      # TODO smontamento dal letto (serve sensore affidabile)
    condition:
      condition: and
      conditions:
        # Entro una certa ora di "mattina"
        - condition: time
          after: !secret day_mode_window_start
          before: !secret day_mode_window_end
        # Eravamo in modalità notte
        - condition: state
          entity_id: input_select.house_mode
          state: night
    action:
      - action: input_select.select_option
        data:
          entity_id: input_select.house_mode
          option: "{{ 'day_working' if is_state('binary_sensor.workday', 'on') else 'day_not_working' }}"

  # Impostazione automatica modalità casa vuota lunga
  - alias: mode_auto_extended_away
    trigger:
      - trigger: state
        entity_id: input_select.house_mode
        to: away
        for: !secret extended_away_period
    action:
      - action: input_select.select_option
        data:
          entity_id: input_select.house_mode
          option: extended_away

  # Per debug: notifica cambio house mode
  - alias: notify_mode_change
    initial_state: true
    trigger:
      - trigger: state
        entity_id: input_select.house_mode
        to:
    action:
      - action: script.notify_debug
        data:
          message: |-
            House mode: {{ states.input_select.house_mode.state }}

script:

  house_mode_night:
    description: Attiva la modalità notte
    sequence:
      - action: input_select.select_option
        data:
          entity_id: input_select.house_mode
          option: night
