# HVAC systems

homeassistant:
  customize:
    climate.boiler_main:
      friendly_name: Riscaldamento
    automation.ThermostatDown:
      friendly_name: Termostato irraggiungibile
    automation.ThermostatStuck:
      friendly_name: Termostato bloccato

shell_command:

  thermorasp_publish_temperature_bedroom: >-
    mosquitto_pub
    -h thermostat.domonet
    -t homeassistant/thermorasp/sensor/temp_bedroom/control
    -m '{"type":"temperature", "validity": 900, "unit": "celsius", "value": {{ states.sensor.temperature_bedroom.state }}}'

  thermorasp_publish_temp_living: >-
    mosquitto_pub
    -h thermostat.domonet
    -t homeassistant/thermorasp/sensor/temp_living/control
    -m '{"type":"temperature", "validity": 900, "unit": "celsius", "value": {{ states.sensor.temperature_living.state }}}'

automation:

  # Termostato down
  - alias: thermostat_down
    trigger:
      - platform: state
        entity_id: device_tracker.thermostat
        to: 'not_home'
        for:
          minutes: 8
    action:
      service: notify.kontalk_daniele
      data_template:
        title: "Allarme"
        message: |-
          Termostato non raggiungibile!

  # Termostato up - pubblica le temperature
  - alias: thermostat_up
    trigger:
      - platform: state
        entity_id: device_tracker.thermostat
        to: 'home'
    action:
      - service: automation.trigger
        entity_id:
          - automation.thermorasp_publish_temperature_bedroom
          - automation.thermorasp_publish_temp_living

  # Termostato bloccato (caldaia accesa)
  - alias: thermostat_stuck
    trigger:
      - platform: state
        entity_id: climate.boiler_main
        to: 'heat'
        for:
          hours: 8
    action:
      service: notify.kontalk_daniele
      data_template:
        title: "Allarme"
        message: |-
          Riscaldamento attivo da più di 6 ore!

  - alias: thermorasp_publish_temperature_bedroom
    trigger:
      - platform: state
        entity_id: sensor.temperature_bedroom
      # Il termostato richiede comunque un aggiornamento ogni 900 secondi
      - platform: time_pattern
        minutes: "/10"
    action:
      - service: shell_command.thermorasp_publish_temperature_bedroom
      #- service: mqtt.publish
      #  data_template:
      #    topic: "homeassistant/thermorasp/sensor/temp_bedroom/control"
      #    payload: '{"type":"temperature", "validity": 900, "unit": "celsius", "value": {{ states.sensor.temp_bedroom.state }}}'

  - alias: thermorasp_publish_temp_living
    trigger:
      - platform: state
        entity_id: sensor.temperature_living
      # Il termostato richiede comunque un aggiornamento ogni 900 secondi
      - platform: time_pattern
        minutes: "/10"
    action:
      - service: shell_command.thermorasp_publish_temp_living
      #- service: mqtt.publish
      #  data_template:
      #    topic: "homeassistant/thermorasp/sensor/temp_living/control"
      #    payload: '{"type":"temperature", "validity": 900, "unit": "celsius", "value": {{ states.sensor.temperature_living.state }}}'

  - alias: thermorasp_set_target_temperature
    trigger:
      - platform: mqtt
        topic: 'homeassistant/_internal/thermorasp/target_temperature'
    action:
      - service: script.boiler_main_set_target_temperature
        data:
          temperature: '{{ trigger.payload }}'

rest_command:

  # 12:34:00.787 XHRPOSThttp://thermostat.local/api/schedules/active/volatile
  #    {"name":"generic.TargetTemperatureBehavior","order":0,"start_time":7954,"end_time":8640,"config":{"target_temperature":22.5},"sensors":["temp_bedroom"],"devices":["home_boiler"]}

  boiler_main_set_active_volatile_generic:
    url: !secret thermostat_set_active_volatile_url
    verify_ssl: false
    method: post
    payload: >-
      {
        "name": "generic.TargetTemperatureBehavior",
        "order": 0,
        "start_time": {{start_time}},
        "end_time": {{end_time}},
        "config": {
          "target_temperature": {{target_temperature}}
        },
        "sensors": [{{sensors}}],
        "devices":[{{devices}}]
      }
    content_type:  'application/json; charset=utf-8'

sensor:

  - platform: command_line
    name: current_minute_for_hvac
    command: "bin/current_minute.py"

  - platform: command_line
    name: today_last_minute_for_hvac
    command: "bin/today_last_minute.py"

script:

  boiler_main_set_target_temperature:
    sequence:
      - service: rest_command.boiler_main_set_active_volatile_generic
        data:
          start_time: '{{ states.sensor.current_minute_for_hvac.state }}'
          end_time: '{{ states.sensor.today_last_minute_for_hvac.state }}'
          target_temperature: '{{ temperature }}'
          # FIXME not pretty
          sensors: '"temp_living","temp_bedroom"'
          # FIXME not pretty
          devices: '"home_boiler"'

climate:

  # Termostato principale
  - platform: mqtt
    name: boiler_main
    precision: 0.1
    temp_step: 0.5
    min_temp: 10
    max_temp: 30
    modes:
      - 'off'
      - 'heat'
    #current_temperature_topic: ''
    #current_temperature_template: '{{ value_json.xxx }}'
    mode_state_topic: 'homeassistant/thermorasp/device/home_boiler/state'
    mode_state_template: "{{ 'heat' if value_json.enabled else 'off' }}"
    temperature_state_topic: 'homeassistant/thermorasp/behavior/active'
    temperature_state_template: '{{ value_json.config.target_temperature }}'
    temperature_command_topic: 'homeassistant/_internal/thermorasp/target_temperature'

  # Condizionatore salone
  - platform: tasmota_irhvac
    name: living_ac
    command_topic: "homeassistant/tasmota/cmnd/living_ac/irhvac"
    state_topic: "homeassistant/tasmota/tele/living_ac/RESULT"
    temperature_sensor: sensor.temperature_living
    protocol: "GREE"
    hvac_model: "YAW1F"
    min_temp: 15
    max_temp: 30
    target_temp: 26
    initial_operation_mode: "off"
    #away_temp: 24
    precision: 1.0
    supported_modes:
      - heat
      - cool
      - dry
      - fan_only
      - auto
      - "off"
    supported_fan_speeds:
      #- low
      - max
      - medium
      # - high
      #- middle
      #- focus
      #- diffuse
      - min
      - auto
    supported_swing_list:
      - "off"
      - vertical #up to down
      # auto ?
