# House lights
# TODO lasciare qui dentro solo la definizione delle entità delle luci

#Bagno 1(main):"Shelly1MiniG3-84FCE63E2ACC"
#Corridoio(Giorno):"Shelly1MiniG3-84FCE63DA950"
#Camera(main):"Shelly1MiniG3-84FCE63DAA9C"
#Corridoio(Notte):"Shelly1MiniG3-84FCE63E1BA0"
#Esterno(Soggiorno):"shelly1-BCDDC27735AE"
#Bagno 2:"Shelly1MiniG3-84FCE638FEDC"
#Esterno(Camera):"shelly1-BCDDC2777F13"
#Cucina:"shelly1-BCDDC277305D"
#Lavatrice:"shelly1pm-34945470E289"
#Studio:"Shelly1MiniG3-ECDA3BC571F4"
#Bagno 1(Specchio):"Shelly1MiniG3-84FCE63DAA68"
#Soggiorno(main):"Shelly1MiniG3-ECDA3BC1E014"

homeassistant:
  customize:
    light.external_bedroom:
      friendly_name: Esterno (camera)
    light.external_living:
      friendly_name: Esterno (soggiorno)
    light.living_main:
      friendly_name: Soggiorno
    light.living_stand:
      friendly_name: Piantana soggiorno
    light.living_ceiling:
      friendly_name: Striscia soffitto
    light.living_extra:
      friendly_name: Soggiorno extra
    light.bedroom_main:
      friendly_name: Camera
    light.bedroom_left:
      friendly_name: Camera SX
    light.kitchen_main:
      friendly_name: Cucina
    light.studio:
      friendly_name: Studio
    light.dayway:
      friendly_name: Corridoio giorno
    light.nightway:
      friendly_name: Corridoio notte
    light.bathroom1_main:
      friendly_name: Bagno 1
    light.bathroom1_mirror:
      friendly_name: Bagno 1 specchio

automation:
  # FIXME appartiene a firmware o devices?
  - alias: "Sync Tasmota states on start-up"
    initial_state: true
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: mqtt.publish
        data:
          topic: "cmnd/tasmotas/state"
          payload: ""

light:

  - platform: template
    lights:
      living_ceiling:
        value_template: "{{ states('light.living_ceiling_real') }}"
        level_template: "{{ state_attr('light.living_ceiling_real', 'brightness') | int(0) }}"
        temperature_template: "{{ state_attr('light.living_ceiling_real', 'color_temp') | int(0) | default(400, true) }}"
        turn_on:
          service: light.turn_on
          data:
            entity_id: light.living_ceiling_real
            brightness: 255
            color_temp: "{{ state_attr('light.living_ceiling_real', 'color_temp') | int(0) | default(400, true) }}"
        turn_off:
          service: light.turn_on
          data:
            entity_id: light.living_ceiling_real
            brightness: 0
            color_temp: "{{ state_attr('light.living_ceiling_real', 'color_temp') | int(0) | default(400, true) }}"
        set_level:
          service: light.turn_on
          data:
            entity_id: light.living_ceiling_real
            brightness: "{{ brightness }}"
        set_temperature:
          service: light.turn_on
          data:
            entity_id: light.living_ceiling_real
            color_temp: "{{ color_temp }}"

  - platform: group
    name: living_extra
    entities:
      - light.living_stand
      - light.living_ceiling

  - platform: group
    name: external
    entities:
      - light.external_living
      - light.external_bedroom

mqtt:
  light:
    - name: "living_stand"
      state_topic: "homeassistant/tasmota/stat/piantana/RESULT"
      state_value_template: "{{ value_json.POWER }}"
      command_topic: "homeassistant/tasmota/cmnd/piantana/POWER"
      payload_on: "ON"
      payload_off: "OFF"
      availability_topic: "homeassistant/tasmota/tele/piantana/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
      qos: 1
      retain: false

script:

  toggle_living_extra:
    sequence:
      - service: light.toggle
        entity_id: light.living_extra
      - wait_template: "{{ as_timestamp(now()) - as_timestamp(states.light.living_extra.last_changed) < 1 }}"
      - service_template: >
          {% if is_state('light.living_extra', 'on') %}
          input_boolean.turn_on
          {% else %}
          input_boolean.turn_off
          {% endif %}
        entity_id: input_boolean.need_living_utility_light

scene:

  # Luci ingresso in casa
  # TODO spostare dove?
  - name: house_entrance
    entities:
      light.living_ceiling:
        state: on
        brightness: 255
        color_temp: 400
      light.living_stand:
        state: on
      input_boolean.house_entrance_lights:
        state: on
