# Media players
# FIXME questo file contiene automazioni che gestiscono in concerto i media_player: riorganizzare/rinominare/splittare

homeassistant:
  customize:
    media_player.kodi:
      friendly_name: Kodi

    media_player.tv:
      friendly_name: TV

    media_player.snapcast_living:
      friendly_name: Music - Living

    media_player.snapcast_bedroom:
      friendly_name: Music - Bedroom

    media_player.snapcast_bathroom:
      friendly_name: Music - Bathroom

    media_player.snapcast_cfba28f0_3339_48ea_80e6_7426830806fe:
      friendly_name: Music - Mobile Daniele

    media_player.snapcast_kitchen:
      friendly_name: Music - Kitchen

    binary_sensor.tv_on_kodi:
      friendly_name: TV source set to Kodi

media_source:

group:

  # Tutti i media
  media:
    name: Media
    icon: mdi:television-classic
    entities:
      # conflicts with Kodi - media_player.tv
      - media_player.kodi
      - media_player.music
      - media_player.bedroom

  # Media non coinvolti in Assist
  media_non_assist:
    name: Media non assist
    icon: mdi:television-classic
    entities:
      # conflicts with Kodi - media_player.tv
      - media_player.kodi
      - media_player.music
      - media_player.bedroom

  # Media che producono i suoni principali (living room)
  # Usato per mettere in pausa quando deve parlare Assist
  media_big_sound:
    name: Media grandi suoni
    icon: mdi:speaker
    entities:
      # Non affidabile: in standby sparisce l'IP; comunque la TV è gestita da Kodi
      #- media_player.tv
      - media_player.kodi
      - media_player.music

  media_audio_only:
    name: Media solo audio
    icon: mdi:speaker
    entities:
      - media_player.kodi
      - media_player.music
      - media_player.bedroom

  # Musica per casa
  media_music_rooms:
    name: Musica
    icon: mdi:music
    entities:
      - media_player.snapcast_living
      - media_player.snapcast_bedroom
      - media_player.snapcast_kitchen
      - media_player.snapcast_cfba28f0_3339_48ea_80e6_7426830806fe

command_line:
  - sensor:
      name: news_tv_channelid
      command: bin/tv-channel.sh "{{ states('input_text.news_tv_channel_name') }}"
      scan_interval: 600

template:
  - binary_sensor:
      # TV accesa su Kodi
      - name: tv_on_kodi
        state: >-
          {{ is_state('media_player.tv', 'on') and is_state_attr('media_player.tv', 'source', 'PC') }}

      # Modalità visione video/cinema o TV in canale
      - name: cinema_mode
        state: >-
          {{ (is_state('media_player.kodi', 'playing') and states.media_player.kodi.attributes.media_content_type in ['movie','tvshow','video']) or
             (is_state('media_player.tv', 'on') and states.media_player.tv.attributes.media_content_type == 'channel') }}

      # Modalità cinema in pausa
      # Pausa di Kodi oppure TV muta
      - name: cinema_paused_mode
        state: >-
          {{ (is_state('media_player.kodi', 'paused') and states.media_player.kodi.attributes.media_content_type in ['movie','tvshow','video']) or
             (is_state('media_player.tv', 'on') and is_state_attr('media_player.tv', 'is_volume_muted', true) and states.media_player.tv.attributes.media_content_type == 'channel') }}

script:
  tv_channel_favourite_news:
    sequence:
      - action: media_player.turn_on
        entity_id: media_player.tv
      - action: media_player.play_media
        data:
          entity_id: media_player.kodi
          media_content_type: 'channel'
          media_content_id: "{{ states('sensor.news_tv_channelid') }}"

  # Pronuncia qualcosa
  say_something:
    sequence:
      # Metti tutto in pausa
      - action: script.suspend_media_for_assist
      - action: assist_satellite.announce
        data:
          # not supported by Amazon Polly -- language: "{{ language|default('it') }}"
          message: "<p>{{ message }}</p>"
          preannounce: false
        target:
          entity_id: assist_satellite.voice_living

  # Pronuncia qualcosa da un audio di TTS pregenerato
  say_something_rendered:
    sequence:
      # Metti tutto in pausa
      # TODO convert this into automation on state=playing or something
      - action: script.suspend_media_for_assist
      - action: assist_satellite.announce
        data:
          media_id: "{{ url }}"
          preannounce: false
        target:
          entity_id: assist_satellite.voice_living

  # Sospende tutti i media per una riproduzione da assist imminente
  suspend_media_for_assist:
    sequence:
      # Pausa tutti i media grandi suoni
      - action: media_player.media_pause
        data:
          entity_id: group.media_big_sound

  # Workaround for Philips API that acts as toggle mute always
  mute_tv:
    sequence:
      - condition: template
        value_template: "{{ is_state_attr('media_player.tv', 'is_volume_muted', false) }}"
      # FIXME Philips API seems to act as toggle always
      - action: media_player.volume_mute
        data:
          entity_id: media_player.tv
          is_volume_muted: true

  # Workaround for Philips API that acts as toggle mute always
  unmute_tv:
    sequence:
      - condition: template
        value_template: "{{ is_state_attr('media_player.tv', 'is_volume_muted', true) }}"
      # FIXME Philips API seems to act as toggle always
      - action: media_player.volume_mute
        data:
          entity_id: media_player.tv
          is_volume_muted: false

input_select:
  kodi_last_media:
    options:
      - none
      - movie
      - tvshow
      - video
      - music

input_text:
  volume_preduck:
    name: Volume pre-duck
    initial: "0.5"
  news_tv_channel_name:
    name: TV news channel

automation:

  - alias: tv_request_turn_on
    id: da684c17-b7aa-4cca-b5ea-0915affdad65
    trigger:
      - trigger: device
        device_id: 91f5981788a21313c9056f8ba1de975f
        domain: webostv
        type: webostv.turn_on
    action:
      action: kodi.call_method
      data:
        entity_id: media_player.kodi
        method: Addons.ExecuteAddon
        addonid: script.module.json-cec
        params:
          command: activate

  - alias: kodi_request_turn_on
    id: 54ce233d-e337-4cd3-b580-2e32c18d9a8b
    trigger:
      trigger: device
      device_id: 990074f3127e3df453ac96e856d47c37
      domain: kodi
      entity_id: media_player.kodi
      type: turn_on
    action:
      - action: wake_on_lan.send_magic_packet
        data:
          mac: !secret mediarasp_mac_address

  - alias: kodi_request_turn_off
    id: 63fd6e16-461b-4d3c-b230-13c1a9575812
    trigger:
      trigger: device
      device_id: 990074f3127e3df453ac96e856d47c37
      domain: kodi
      entity_id: media_player.kodi
      type: turn_off
    action:
      - action: media_player.media_stop
        entity_id: media_player.kodi
      - action: kodi.call_method
        data:
          entity_id: media_player.kodi
          method: Addons.ExecuteAddon
          addonid: script.module.json-cec
          params:
            command: standby

  - alias: update_kodi_last_media
    id: db64c63b-7f7a-481f-88dd-f9b3fdb69515
    trigger:
      - trigger: state
        entity_id: 'media_player.kodi'
        to: 'playing'
    action:
      - action: input_select.select_option
        data:
          entity_id: input_select.kodi_last_media
          option: "{{ states.media_player.kodi.attributes.media_content_type }}"

  - alias: pause_on_phone_call
    id: 0fd523cb-57e9-4c72-89ac-91068c473b8f
    trigger:
      - trigger: state
        entity_id: sensor.daniele_shiba_phone_state
        from: 'idle'
      - trigger: state
        entity_id: sensor.shiba_phone_call_incoming_caller
        from: ''
    action:
      # Chiamata entrante o uscente, pausa i media grandi suoni
      - action: media_player.media_pause
        data:
          entity_id: group.media_big_sound
      # notify to Kodi if TV is on and on the right source
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.tv_on_kodi
                state: 'on'
              - condition: state
                entity_id: sensor.daniele_shiba_phone_state
                state: 'ringing'
            sequence:
              - action: notify.kodi
                data:
                  title: "Chiamata in arrivo"
                  message: "Chiamata in arrivo da {{ states('sensor.shiba_phone_call_incoming_caller') }}"

  - alias: pause_music_on_video_start
    id: 5bba969f-430f-4155-a109-ae589a674293
    trigger:
      - trigger: state
        entity_id: media_player.kodi
        to: 'playing'
    action:
      # Pausa musica
      - action: media_player.media_pause
        data:
          entity_id: media_player.music

  - alias: pause_video_on_music_start
    id: c0b7f7d5-51f4-459a-b107-b44e5efa2c87
    trigger:
      - trigger: state
        entity_id: media_player.music
        to: 'playing'
    action:
      # Pausa Kodi
      - action: media_player.media_pause
        data:
          entity_id: media_player.kodi

  # Abbassa la musica quando non c'è attività in soggiorno
  - alias: duck_volume_living
    id: bdfe839c-28a7-49f2-9a59-0c41d00b6450
    trigger:
      - trigger: state
        entity_id: group.motion_living
        to: 'off'
    action:
      - action: input_text.set_value
        data:
          entity_id: input_text.volume_preduck
          value: '{{ states.media_player.snapcast_living.attributes.volume_level }}'
      # Se abbiamo bisogno di luce in sala non proseguire
      # Abbiamo comunque impostato il volume pre-duck
      - condition: state
        entity_id: input_boolean.need_living_utility_light
        state: 'off'
      # Se notebook attivo non proseguire
      # Abbiamo comunque impostato il volume pre-duck
      - condition: state
        entity_id: binary_sensor.activity_notebook_daniele
        state: 'off'
      - action: media_player.volume_set
        data:
          # Living
          entity_id: media_player.snapcast_living
          volume_level: !secret music_duck_volume

  # Ripristina volume della musica quando c'è attività in soggiorno
  - alias: unduck_volume_living
    id: 4ef4cc14-e714-45b8-8cae-c41bb30c65dd
    trigger:
      - trigger: state
        entity_id: group.motion_living
        to: 'on'
    action:
      - action: media_player.volume_set
        data:
          entity_id: media_player.snapcast_living
          volume_level: '{{ states.input_text.volume_preduck.state }}'

  # Se bedroom in pausa da più di tot tempo, stoppalo
  - alias: stop_speaker_bedroom_if_paused
    id: 85dacd22-69df-4711-b008-11c881ed7787
    trigger:
      - trigger: state
        entity_id: media_player.bedroom
        to: 'paused'
        for: '00:05:00'
    action:
      - action: media_player.media_stop
        entity_id: media_player.bedroom

  - alias: trigger_mediarasp_update
    id: 367e1f33-0da5-4f1b-b606-3a6a7fae72bf
    trigger:
      trigger: mqtt
      topic: mopidy/music/i/sta
    action:
      - action: homeassistant.update_entity
        data:
          entity_id: media_player.music

  - alias: trigger_speaker_bedroom_update
    id: 9a3fbfe4-8933-4e99-84c5-1a3c3c976589
    trigger:
      trigger: mqtt
      topic: mopidy/bedroom/i/sta
    action:
      - action: homeassistant.update_entity
        data:
          entity_id: media_player.bedroom

  - alias: kodi_crash_workaround
    id: 481b4dd3-b47e-43d0-9719-9cadc4c7f617
    description: Spegni la TV dopo un crash di Kodi se nessuno sta guardando
    trigger:
      trigger: state
      # il media player non supporta gli stati on/off apparentemente
      entity_id: device_tracker.tv
      to: "home"
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: input_select.house_mode
          state: night
        - condition: state
          entity_id: input_select.house_mode
          state: away
        - condition: state
          entity_id: input_select.house_mode
          state: extended_away
    action:
      - action: media_player.turn_off
        entity_id: media_player.kodi
      # Questo potrebbe fallire quindi lo mettiamo per ultimo
      - action: media_player.turn_off
        entity_id: media_player.tv

  - alias: bathroom_activate_media_controller
    id: c53ca555-9fbc-47d1-aab7-e76230a1a77f
    description: Attiva BubbleUPnP sul telefono quando lo speaker in bagno si connette
    trigger:
      trigger: state
      entity_id: media_player.snapcast_bathroom
      to: "idle"
    condition:
      condition: state
      entity_id: person.daniele
      state: home
    action:
      - action: notify.mobile_app_daniele_shiba
        data:
          message: command_broadcast_intent
          data:
            intent_package_name: "com.bubblesoft.android.bubbleupnp"
            intent_action: "com.bubblesoft.android.bubbleupnp.START_SERVICE"
      - delay: 6
      - action: notify.mobile_app_daniele_shiba
        data:
          message: command_broadcast_intent
          data:
            intent_package_name: "com.bubblesoft.android.bubbleupnp"
            intent_action: "com.bubblesoft.android.bubbleupnp.SET_RENDERER"
            intent_extras: "name:Music House (OpenHome)"
