# Media players

homeassistant:
  customize:
    media_player.kodi:
      friendly_name: Kodi

    media_player.tv:
      friendly_name: TV

    media_player.lounge:
      friendly_name: Lounge

media_player:
  - platform: kodi
    host: rasp
    name: kodi
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: !secret mediarasp_mac_address
    turn_off_action:
      - service: media_player.media_stop
        entity_id: media_player.kodi
      - service: kodi.call_method
        data:
          entity_id: media_player.kodi
          method: Addons.ExecuteAddon
          addonid: script.json-cec
          params:
            command: standby
  - platform: philips_js
    host: !secret tv_ip_address
    name: tv
    api_version: 1
    turn_on_action:
      service: kodi.call_method
      data:
        entity_id: media_player.kodi
        method: Addons.ExecuteAddon
        addonid: script.json-cec
        params:
          command: activate

group:

  # Tutti i media
  media:
    name: Media
    icon: mdi:television-classic
    entities:
      - media_player.tv
      - media_player.kodi
      - media_player.lounge

  # Media non coinvolti nel TTS
  media_non_tts:
    name: Media
    icon: mdi:television-classic
    entities:
      - media_player.tv
      - media_player.kodi

binary_sensor:

  - platform: template
    sensors:
      # Modalità visione video/cinema o TV in canale
      cinema_mode:
        entity_id:
          - media_player.kodi
          - media_player.tv
        value_template: >-
          {{ (is_state('media_player.kodi', 'playing') and states.media_player.kodi.attributes.media_content_type in ['movie','tvshow','video']) or
             (is_state('media_player.tv', 'on') and states.media_player.tv.attributes.media_content_type == 'channel') }}

      # Modalità cinema in pausa
      # Pausa di Kodi oppure TV muta
      cinema_paused_mode:
        entity_id:
          - media_player.kodi
          - media_player.tv
        value_template: >-
          {{ (is_state('media_player.kodi', 'paused') and states.media_player.kodi.attributes.media_content_type in ['movie','tvshow','video']) or
             (is_state('media_player.tv', 'on') and is_state_attr('media_player.tv', 'is_volume_muted', true) and states.media_player.tv.attributes.media_content_type == 'channel') }}


# FIXME le API di Philipsmerda non funzionano per cambiare canale, quindi facciamo finta di digitarlo
# Canale 507 (La7 HD)
rest_command:
  tv_channel_favourite_news_digit1:
    url: http://192.168.0.205:1925/1/input/key
    method: post
    payload: '{"key": "Digit0"}'
  tv_channel_favourite_news_digit2:
    url: http://192.168.0.205:1925/1/input/key
    method: post
    payload: '{"key": "Digit5"}'
  tv_channel_favourite_news_digit3:
    url: http://192.168.0.205:1925/1/input/key
    method: post
    payload: '{"key": "Digit0"}'
  tv_channel_favourite_news_digit4:
    url: http://192.168.0.205:1925/1/input/key
    method: post
    payload: '{"key": "Digit7"}'

script:
  tv_channel_favourite_news:
    sequence:
      - service: media_player.turn_on
        entity_id: media_player.tv
      - wait_template: "{{ is_state('media_player.tv', 'on') and is_state('device_tracker.tv', 'home') }}"
        timeout: '00:00:60'
      - service: media_player.select_source
        data:
          entity_id: media_player.tv
          source: "Input: Watch TV"
      - wait_template: "{{ is_state_attr('media_player.tv', 'media_content_type', 'channel') }}"
        timeout: '00:00:30'
      - service: rest_command.tv_channel_favourite_news_digit1
      - delay:
          seconds: 1
      - service: rest_command.tv_channel_favourite_news_digit2
      - delay:
          seconds: 1
      - service: rest_command.tv_channel_favourite_news_digit3
      - delay:
          seconds: 1
      - service: rest_command.tv_channel_favourite_news_digit4

  # Pronuncia qualcosa
  say_something:
    sequence:
      # Metti tutto in pausa
      - service: script.suspend_media_for_lounge
      # Ferma la riproduzione da lounge
      - service: media_player.media_stop
        entity_id: media_player.lounge
      - service: script.set_tts_volume
      - service: tts.amazon_polly_say
        entity_id: media_player.lounge
        data_template:
          # not supported by Amazon Polly -- language: "{{ language|default('it') }}"
          message: "<speak>{{ message }}</speak>"

  # Un buon volume per la pronuncia
  set_tts_volume:
    sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.lounge
          volume_level: !secret lounge_volume

  # Sospende tutti i media per una riproduzione da lounge imminente
  suspend_media_for_lounge:
    sequence:
      # Pausa Kodi
      - service: media_player.media_pause
        data:
          entity_id: media_player.kodi
      # Muta la TV
      - condition: state
        entity_id: media_player.tv
        state: 'on'
      - service: media_player.volume_mute
        data:
          entity_id: media_player.tv
          is_volume_muted: true
