# Media players

homeassistant:
  customize:
    media_player.kodi:
      friendly_name: Kodi

    media_player.tv:
      friendly_name: TV

    media_player.lounge:
      friendly_name: Music - Lounge

    media_player.snapcast_living:
      friendly_name: Music - Living

    media_player.snapcast_bedroom:
      friendly_name: Music - Bedroom

    media_player.snapcast_bathroom:
      friendly_name: Music - Bathroom

    media_player.snapcast_cfba28f0_3339_48ea_80e6_7426830806fe:
      friendly_name: Music - Mobile Daniele

    media_player.snapcast_kitchen:
      friendly_name: Music - Kitchen

media_player:
  - platform: kodi
    host: rasp
    name: kodi
    # turn_on_action no longer supported
    # turn_off_action no longer supported
  - platform: mpd
    host: !secret mediarasp_ip_address
    name: music
  - platform: snapcast
    host: !secret mediarasp_ip_address
  - platform: mpd
    host: !secret speaker_bedroom_host
    name: bedroom

group:

  # Tutti i media
  media:
    name: Media
    icon: mdi:television-classic
    entities:
      - media_player.tv
      - media_player.kodi
      - media_player.lounge
      - media_player.music
      - media_player.bedroom

  # Media non coinvolti nel TTS
  media_non_tts:
    name: Media non TTS
    icon: mdi:television-classic
    entities:
      - media_player.tv
      - media_player.kodi
      - media_player.music
      - media_player.bedroom

  # Media che producono i suoni principali (living room)
  # Usato per mettere in pausa quando deve parlare il TTS
  media_big_sound:
    name: Media grandi suoni
    icon: mdi:speaker
    entities:
      # Non affidabile: in standby sparisce l'IP; comunque la TV è gestita da Kodi
      #- media_player.tv
      - media_player.kodi
      - media_player.music

  media_audio_only:
    name: Media solo audio
    icon: mdi:speaker
    entities:
      - media_player.kodi
      - media_player.music
      - media_player.bedroom

  # Musica per casa
  media_music_rooms:
    name: Musica
    icon: mdi:music
    entities:
      - media_player.snapcast_living
      - media_player.snapcast_bedroom
      - media_player.snapcast_kitchen
      - media_player.snapcast_cfba28f0_3339_48ea_80e6_7426830806fe

binary_sensor:

  - platform: template
    sensors:
      # Modalità visione video/cinema o TV in canale
      cinema_mode:
        value_template: >-
          {{ (is_state('media_player.kodi', 'playing') and states.media_player.kodi.attributes.media_content_type in ['movie','tvshow','video']) or
             (is_state('media_player.tv', 'on') and states.media_player.tv.attributes.media_content_type == 'channel') }}

      # Modalità cinema in pausa
      # Pausa di Kodi oppure TV muta
      cinema_paused_mode:
        value_template: >-
          {{ (is_state('media_player.kodi', 'paused') and states.media_player.kodi.attributes.media_content_type in ['movie','tvshow','video']) or
             (is_state('media_player.tv', 'on') and is_state_attr('media_player.tv', 'is_volume_muted', true) and states.media_player.tv.attributes.media_content_type == 'channel') }}


# FIXME le API di Philipsmerda non funzionano per cambiare canale, quindi facciamo finta di digitarlo
# Canale 507 (La7 HD)
rest_command:
  tv_channel_favourite_news_digit1:
    url: http://192.168.0.205:1925/1/input/key
    method: post
    payload: '{"key": "Digit0"}'
  tv_channel_favourite_news_digit2:
    url: http://192.168.0.205:1925/1/input/key
    method: post
    payload: '{"key": "Digit5"}'
  tv_channel_favourite_news_digit3:
    url: http://192.168.0.205:1925/1/input/key
    method: post
    payload: '{"key": "Digit0"}'
  tv_channel_favourite_news_digit4:
    url: http://192.168.0.205:1925/1/input/key
    method: post
    payload: '{"key": "Digit7"}'

script:
  tv_channel_favourite_news:
    sequence:
      - service: media_player.turn_on
        entity_id: media_player.tv
      - service: media_player.play_media
        data:
          entity_id: media_player.kodi
          media_content_type: 'channel'
          media_content_id: !secret tv_news_channel

  # Pronuncia qualcosa
  say_something:
    sequence:
      # Metti tutto in pausa
      - service: script.suspend_media_for_lounge
      # Ferma la riproduzione da lounge
      - service: media_player.media_stop
        entity_id: media_player.lounge
      - service: script.set_tts_volume
      - service: tts.microsoft_say
        entity_id: media_player.lounge
        data_template:
          # not supported by Amazon Polly -- language: "{{ language|default('it') }}"
          message: "<p>{{ message }}</p>"

  # Pronuncia qualcosa da un audio di TTS pregenerato
  say_something_rendered:
    sequence:
      # Metti tutto in pausa
      - service: script.suspend_media_for_lounge
      # Ferma la riproduzione da lounge
      - service: media_player.media_stop
        entity_id: media_player.lounge
      - service: script.set_tts_volume
      - service: media_player.play_media
        data_template:
          entity_id: media_player.lounge
          media_content_type: music
          media_content_id: "{{ url }}"

  # Un buon volume per la pronuncia
  set_tts_volume:
    sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.lounge
          volume_level: !secret lounge_volume

  # Sospende tutti i media per una riproduzione da lounge imminente
  suspend_media_for_lounge:
    sequence:
      # Pausa tutti i media grandi suoni
      - service: media_player.media_pause
        data:
          entity_id: group.media_big_sound
      # Muta la TV
      - condition: state
        entity_id: media_player.tv
        state: 'on'
      - service: script.mute_tv

  # Workaround for Philips API that acts as toggle mute always
  mute_tv:
    sequence:
      - condition: template
        value_template: "{{ is_state_attr('media_player.tv', 'is_volume_muted', false) }}"
      # FIXME Philips API seems to act as toggle always
      - service: media_player.volume_mute
        data:
          entity_id: media_player.tv
          is_volume_muted: true

  # Workaround for Philips API that acts as toggle mute always
  unmute_tv:
    sequence:
      - condition: template
        value_template: "{{ is_state_attr('media_player.tv', 'is_volume_muted', true) }}"
      # FIXME Philips API seems to act as toggle always
      - service: media_player.volume_mute
        data:
          entity_id: media_player.tv
          is_volume_muted: false

input_select:
  kodi_last_media:
    options:
      - none
      - movie
      - tvshow
      - video
      - music

input_text:
  volume_preduck:
    name: Volume pre-duck
    initial: 0.5

automation:

  - alias: tv_request_turn_on
    trigger:
      - platform: device
        device_id: f689398559355f452b4318b3e9d21947
        domain: philips_js
        type: turn_on
    action:
      service: kodi.call_method
      data:
        entity_id: media_player.kodi
        method: Addons.ExecuteAddon
        addonid: script.json-cec
        params:
          command: activate

  - alias: kodi_request_turn_on
    trigger:
      platform: device
      device_id: db9f8246f92511ea9a5be195168bca21
      domain: kodi
      entity_id: media_player.kodi
      type: turn_on
    action:
      - service: wake_on_lan.send_magic_packet
        data:
          mac: !secret mediarasp_mac_address

  - alias: kodi_request_turn_off
    trigger:
      platform: device
      device_id: db9f8246f92511ea9a5be195168bca21
      domain: kodi
      entity_id: media_player.kodi
      type: turn_off
    action:
      - service: media_player.media_stop
        entity_id: media_player.kodi
      - service: kodi.call_method
        data:
          entity_id: media_player.kodi
          method: Addons.ExecuteAddon
          addonid: script.json-cec
          params:
            command: standby

  - alias: update_kodi_last_media
    trigger:
      - platform: state
        entity_id: 'media_player.kodi'
        to: 'playing'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.kodi_last_media
          option: "{{ states.media_player.kodi.attributes.media_content_type }}"

  - alias: pause_on_phone_call
    trigger:
      - platform: state
        entity_id: sensor.daniele_payton_phone_state
        from: 'idle'
    action:
      # Chiamata entrante o uscente, pausa i media grandi suoni
      - service: media_player.media_pause
        data:
          entity_id: group.media_big_sound
      # Muta la TV
      - condition: state
        entity_id: media_player.tv
        state: 'on'
      - service: script.mute_tv

  - alias: pause_music_on_video_start
    trigger:
      - platform: state
        entity_id: media_player.kodi
        to: 'playing'
    action:
      # Pausa musica
      - service: media_player.media_pause
        data:
          entity_id: media_player.music

  - alias: pause_video_on_music_start
    trigger:
      - platform: state
        entity_id: media_player.music
        to: 'playing'
    action:
      # Pausa Kodi
      - service: media_player.media_pause
        data:
          entity_id: media_player.kodi

  # Abbassa la musica quando non c'è attività in salone
  - alias: duck_volume_living
    trigger:
      - platform: state
        entity_id: group.motion_living
        to: 'off'
    condition:
    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.volume_preduck
          value: '{{ states.media_player.snapcast_living.attributes.volume_level }}'
      # Se abbiamo bisogno di luce in sala non proseguire
      # Abbiamo comunque impostato il volume pre-duck
      - condition: state
        entity_id: input_boolean.need_living_utility_light
        state: 'off'
      # Se notebook attivo non proseguire
      # Abbiamo comunque impostato il volume pre-duck
      - condition: state
        entity_id: binary_sensor.activity_notebook_daniele
        state: 'off'
      - service: media_player.volume_set
        data:
          # Living
          entity_id: media_player.snapcast_living
          volume_level: !secret music_duck_volume

  # Ripristina volume della musica quando c'è attività in salone
  - alias: unduck_volume_living
    trigger:
      - platform: state
        entity_id: group.motion_living
        to: 'on'
    action:
      - service: media_player.volume_set
        data:
          entity_id: media_player.snapcast_living
          volume_level: '{{ states.input_text.volume_preduck.state }}'
