# FIXME la gestione della notte e del risveglio merita probabilmente una directory dedicata

homeassistant:
  customize:
    input_boolean.night_mode_disabled_today:
      friendly_name: 'Modalità notte disattivata per oggi'
      icon: mdi:weather-night

script:

  night_mode_warning_start:
    sequence:
      - service: timer.cancel
        data:
          entity_id: timer.night_mode_warning
      - service: timer.start
        data:
          entity_id: timer.night_mode_warning
          duration: "00:02:59"

  # Notifica l'utente che sta per attivarsi la modalità notte
  notify_night_mode_warning:
    sequence:
      - service: notify.mobile_app_daniele_payton
        data:
          title: "Modalità notte"
          message: "Sto per attivare la modalità notte!"
          data:
            tag: night_mode_warning
            sticky: 'true'
            priority: high
            ttl: 180
            actions:
              # Rimanda di 15 minuti
              - action: night_mode_snooze
                title: Rimanda
              # Attiva ora
              - action: night_mode_enable_now
                title: Attiva
              # Annulla per questa notte
              - action: night_mode_cancel
                title: Annulla

  # Cancella la notifica della modalità notte
  cancel_night_mode_warning:
    sequence:
      - service: notify.mobile_app_daniele_payton
        data:
          message: clear_notification
          data:
            priority: high
            tag: night_mode_warning

automation:

  # Avvisami che sta per attivarsi la modalità notte
  # Se non ci saranno cambiamenti si attiverà automaticamente in 3 minuti
  - alias: night_mode_warning
    id: bcf91662-890e-41f7-a5bd-c6a55852624b
    trigger:
      platform: time_pattern
      # FIXME hard-coding variables
      # because secrets in templates are not supported
      minutes: "/1"
    condition:
      # Le condizioni sono solo in questa automazione perché
      # dopo il primo triggering la cancellazione viene delegata all'utente.
      condition: and
      conditions:
        # Ora notturna
        - condition: time
          # FIXME hard-coding variables: night_mode_hour_start, night_mode_hour_end
          # because secrets in templates are not supported
          after: '23:00:00'
          before: '04:00:00'
        # Non siamo già in modalità notte
        - condition: template
          value_template: "{{ not is_state('input_select.house_mode', 'night') }}"
        # Modalità notte non disabilitata
        - condition: state
          entity_id: input_boolean.night_mode_disabled_today
          state: 'off'
        # Qualcuno in casa
        - condition: numeric_state
          entity_id: sensor.people_count_home
          above: '0'
        # Tutte i presenti in camera
        # FIXME sensore rimosso
        #- condition: template
        #  value_template: '{{ states.input_number.people_count_bedroom.state | float == states.sensor.people_count_home.state | float }}'
        # Timer warning non attivo
        - condition: template
          value_template: "{{ not is_state('timer.night_mode_warning', 'active') }}"
        # Timer snooze non attivo
        - condition: template
          value_template: "{{ not is_state('timer.night_mode_snooze', 'active') }}"
        # Tutte le luci spente (tranne la luce del letto)
        - condition: template
          value_template: >
            {% set domain = 'light' %}
            {% set state = 'off' %}
            {{ states[domain] | rejectattr('entity_id','eq', 'light.bedroom_left') | list | count ==
              states[domain] | selectattr('state','eq', state) | rejectattr('entity_id','eq', 'light.bedroom_left') | list | count }}
        # Tutte i media idle
        - condition: state
          entity_id: media_player.kodi
          state: idle
        - condition: template
          value_template: "{{ is_state('media_player.music', 'off') or is_state('media_player.music', 'paused') or is_state('media_player.music', 'unavailable')}}"
        - condition: template
          value_template: "{{ is_state('media_player.tv', 'idle') or is_state('media_player.tv', 'off') or is_state('media_player.tv', 'unavailable') }}"
        - condition: template
          value_template: "{{ is_state('device_tracker.tv', 'not_home') or is_state('device_tracker.tv', 'unavailable') }}"
        - condition: template
          value_template: "{{ is_state('media_player.lounge', 'idle') or is_state('media_player.lounge', 'off') or is_state('media_player.lounge', 'unavailable') }}"
        # Ogni movimento tranne in camera da letto cessato
        - condition: state
          entity_id: group.motion_not_bedroom
          state: 'off'
        # Cellulare in carica
        - condition: template
          value_template: "{{ is_state('sensor.daniele_payton_battery_state', 'charging') }}"
        # TODO Cellulare in standby (non in uso)
        # ...
        # Luminosità bassa in tutte le stanze
        - condition: numeric_state
          entity_id: sensor.lux_living
          below: !secret living_lux_darkness_threshold
        - condition: numeric_state
          entity_id: sensor.bedroom_lux
          below: !secret bedroom_lux_darkness_threshold
        # Notebook spento o idle
        - condition: state
          entity_id: binary_sensor.activity_notebook_daniele
          state: 'off'
    action:
      - service: script.night_mode_warning_start

  # Attivazione modalità notte per scadenza del timer
  - alias: night_mode_enable
    id: c365ea4e-2c99-48be-94db-71499fbea546
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.night_mode_warning
    action:
      - service: script.cancel_night_mode_warning
      - service: input_select.select_option
        data:
          entity_id: input_select.house_mode
          option: night

  # Timer warning modalità notte partito
  - alias: night_mode_warning_started
    id: 207bc889-a191-4085-b386-7b1fb69ad5ea
    trigger:
      platform: event
      event_type: timer.started
      event_data:
        entity_id: timer.night_mode_warning
    action:
      # Notifica per override/snooze
      - service: script.notify_night_mode_warning

  # Annullamento del timer di warning della modalità notte
  - alias: night_mode_cancelled
    id: 66b695b7-1043-4346-84aa-22bbe6b4c589
    trigger:
      platform: event
      event_type: timer.cancelled
      event_data:
        entity_id: timer.night_mode_warning
    action:
      - service: script.cancel_night_mode_warning

  # Utente ha richiesto snooze, riavvia il timer per 15 minuti (12 snooze + 3 warning)
  - alias: night_mode_snooze
    id: 56c8fd1b-10b0-43da-b619-d3d9dfdf8b49
    trigger:
      - event_data:
          action: night_mode_snooze
        event_type: mobile_app_notification_action
        platform: event
    action:
      - service: timer.cancel
        data:
          entity_id: timer.night_mode_warning
      - service: timer.cancel
        data:
          entity_id: timer.night_mode_snooze
      - service: timer.start
        data:
          entity_id: timer.night_mode_snooze
          duration: "00:12:00"

  # Scadenza dello snooze della modalità notte
  - alias: night_mode_snoozed
    id: e65a336a-56ab-4974-9324-1680972f9e0c
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.night_mode_snooze
    action:
      # Riavvia timer warning
      - service: script.night_mode_warning_start

  # Utente ha richiesto attivazione immediata
  - alias: night_mode_enable_now
    id: da80db36-5890-4420-bedc-d5fd9bc4e45a
    trigger:
      - event_data:
          action: night_mode_enable_now
        event_type: mobile_app_notification_action
        platform: event
    action:
      - service: timer.finish
        data:
          entity_id: timer.night_mode_warning

  # Utente ha richiesto annullamento per stanotte
  - alias: night_mode_cancel
    id: 93ca163b-9f9f-4766-acee-865078ad58a9
    trigger:
      - event_data:
          action: night_mode_cancel
        event_type: mobile_app_notification_action
        platform: event
    action:
      # Imposta qualche flag per evitare che night_mode_warning si riattivi
      - service: input_boolean.turn_on
        entity_id: input_boolean.night_mode_disabled_today
      - service: timer.cancel
        data:
          entity_id: timer.night_mode_warning

  # Abilita modalità notte disattivata dall'utente la sera prima
  - alias: night_mode_disabled_enable
    id: a855daad-8caa-41b7-9948-b40725c07bd5
    trigger:
      platform: time
      at: "06:00:00"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.night_mode_disabled_today

  - alias: house_mode_night_mode_night
    id: 2153a2c5-751c-455c-be22-a38f274982ed
    trigger:
      - platform: state
        entity_id: input_select.house_mode
        to: night
    action:
      # Usato per far capire all'automazione che non deve attivarsi
      - service: input_boolean.turn_on
        entity_id: input_boolean.night_mode_disabled_today
      # Inutile stare a controllare le condizioni della night mode se ci siamo già
      - service: automation.turn_off
        entity_id:
          - automation.night_mode_warning

  - alias: house_mode_night_mode_not_night
    id: 7ae3d738-102a-4181-b37b-a9c684877187
    trigger:
      - platform: state
        entity_id: input_select.house_mode
        from: night
    action:
      # Riattiva i controlli per la night mode automatica
      - service: automation.turn_on
        entity_id:
          - automation.night_mode_warning

timer:

  night_mode_warning:
    name: Timer notte
    icon: mdi:weather-night

  night_mode_snooze:
    name: Timer snooze notte
    icon: mdi:alarm-snooze

input_boolean:

  # TODO automazione basata su questo booleano che attiva/disattiva le altre (invece di usare il booleano come condizione)
  night_mode_disabled_today:
    initial: off
