# Persons

homeassistant:
  customize:
    person.daniele:
      friendly_name: Daniele
      entity_picture: !secret daniele_picture

person:
  - name: daniele
    id: daniele
    user_id: !secret userid_daniele
    device_trackers:
      - device_tracker.daniele_paytongps
      - device_tracker.daniele_paytonwifi
      - device_tracker.daniele_paytonble

group:
  daniele_devices:
    name: Daniele trackers
    entities:
      - device_tracker.daniele_paytongps
      - device_tracker.daniele_paytonwifi
      - device_tracker.daniele_paytonble
