# Entity state scenes and scenarios for living room

input_boolean:

  need_living_utility_light:
    name: 'Ho bisogno di una luce minima in soggiorno'
    initial: off
    icon: mdi:lighthouse-on

scene:

  - name: dinner_watching
    entities:
      light.living_extra: on
      # TODO light.living_main_light: off
      # TODO light.living_table_light: off

  - name: cinema_mode
    entities:
      light.living_extra: off
      # TODO light.living_main_light: off
      # TODO light.living_table_light: off

  # Luci guida notturne
  - name: living_night_guidance_on
    entities:
      light.living_ceiling:
        state: on
        brightness: 40
        color_temp: 400

  - name: living_night_guidance_off
    entities:
      light.living_ceiling:
        state: off

automation:

  - alias: need_utility_light_on
    trigger:
      - platform: state
        entity_id: input_boolean.need_living_utility_light
        to: 'on'
    condition:
      - condition: state
        entity_id: binary_sensor.living_need_light
        state: 'on'
    action:
      - service: light.turn_on
        entity_id: light.living_extra

  - alias: need_utility_light_off
    trigger:
      - platform: state
        entity_id: input_boolean.need_living_utility_light
        to: 'off'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: 'media_player.kodi'
          state: idle
        - condition: state
          entity_id: binary_sensor.cinema_mode
          state: 'on'
    action:
      - service: light.turn_off
        entity_id: light.living_extra

  - alias: dinner_watching
    trigger:
      - platform: state
        entity_id: 'media_player.kodi'
        to: 'playing'
      - platform: template
        value_template: "{{ is_state_attr('media_player.tv', 'media_content_type', 'channel') }}"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.living_need_light
          state: 'on'
        - condition: state
          entity_id: input_boolean.need_living_utility_light
          state: 'on'
        - condition: state
          entity_id: binary_sensor.cinema_mode
          state: 'on'
    action:
      - service: scene.turn_on
        entity_id: scene.dinner_watching

  - alias: cinema_mode
    trigger:
      - platform: state
        entity_id: 'media_player.kodi'
        to: 'playing'
      - platform: template
        value_template: >-
          {{ is_state('media_player.tv', 'on') and is_state_attr('media_player.tv', 'media_content_type', 'channel') }}
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.need_living_utility_light
          state: 'off'
        - condition: state
          entity_id: binary_sensor.cinema_mode
          state: 'on'
        # Evitiamo di spegnere tutto se siamo appena rientrati
        - condition: state
          entity_id: input_boolean.house_entrance_lights
          state: 'off'
    action:
      - service: scene.turn_on
        entity_id: scene.cinema_mode

  # Accendi luce utility se mettiamo in pausa un video
  - alias: media_paused
    trigger:
      - platform: state
        entity_id: 'media_player.kodi'
        from: 'playing'
        to: 'paused'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.living_need_light
          state: 'on'
        - condition: template
          value_template: '{{ states.media_player.kodi.attributes.media_content_type in ["movie","tvshow","video"] }}'
    action:
      - service: light.turn_on
        entity_id: light.living_ceiling

  # Accendi luce utility se fermiamo Kodi
  - alias: media_stopped
    trigger:
      - platform: state
        entity_id: 'media_player.kodi'
        to: 'idle'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.living_need_light
          state: 'on'
        # Solo se stavo riproducendo video prima
        - condition: template
          value_template: '{{ states.input_select.kodi_last_media.state in ["movie","tvshow","video"] }}'
        # Solo se non siamo in modalità notte (spegnimento kodi causa night mode)
        - condition: template
          value_template: "{{ not is_state('input_select.house_mode', 'night') }}"
    action:
      - service: light.turn_on
        entity_id: light.living_ceiling

  - alias: house_mode_living_guest
    trigger:
      - platform: state
        entity_id: input_select.house_mode
        to: guest
    action:
      - delay:
          seconds: 5
      - service: media_player.play_media
        data_template:
          entity_id: media_player.kodi
          media_content_id: !secret guest_mode_playlist
          media_content_type: music
      - service: media_player.volume_set
        data:
          entity_id: media_player.kodi
          volume_level: !secret guest_mode_volume

  - alias: house_mode_living_not_guest
    trigger:
      - platform: state
        entity_id: input_select.house_mode
        from: guest
    action:
      - service: media_player.media_stop
        entity_id: media_player.kodi
      - service: media_player.volume_set
        data:
          entity_id: media_player.kodi
          volume_level: 0.9

  # Troppa luce in soggiorno: spegni le luci extra
  - alias: living_too_much_light
    trigger:
      - platform: numeric_state
        entity_id: sensor.living_main_lux
        above: !secret living_lux_too_much_threshold
    action:
      - service: light.turn_off
        entity_id: light.living_extra

  - alias: house_mode_living_night
    trigger:
      platform: state
      entity_id: input_select.house_mode
      to: night
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.need_living_utility_light
      - service: media_player.turn_off
        entity_id: media_player.kodi
      # Questo potrebbe fallire quindi lo mettiamo per ultimo
      - service: media_player.turn_off
        entity_id: media_player.tv

  - alias: house_mode_living_away
    trigger:
      platform: state
      entity_id: input_select.house_mode
      to: away
    action:
      - service: media_player.turn_off
        entity_id: media_player.kodi
      - service: media_player.turn_off
        entity_id: media_player.tv
      - service: input_boolean.turn_off
        entity_id: input_boolean.need_living_utility_light

  # Accendi una lieve luce notturna in caso di movimento in salone
  - alias: living_motion_night
    trigger:
      - platform: state
        entity_id: group.living_motion
        to: 'on'
      - platform: numeric_state
        entity_id: sensor.living_main_lux
        below: !secret living_lux_darkness_threshold
    condition:
      condition: and
      conditions:
        # Modalità cinema off
        - condition: state
          entity_id: binary_sensor.cinema_mode
          state: 'off'
        - condition: state
          entity_id: binary_sensor.cinema_paused_mode
          state: 'off'
        # TV spenta (rafforzativo del cinema mode causa instabilità API Philips)
        - condition: state
          entity_id: media_player.tv
          state: 'off'
        # Non mi serve luce utility soggiorno
        - condition: state
          entity_id: input_boolean.need_living_utility_light
          state: 'off'
        # Luce utility spenta
        - condition: state
          entity_id: light.living_extra
          state: 'off'
        # Assicuriamoci che le condizioni del trigger siano tutte rispettate
        - condition: state
          entity_id: group.living_motion
          state: 'on'
        - condition: numeric_state
          entity_id: sensor.living_main_lux
          below: !secret living_lux_darkness_threshold
    action:
      - service: scene.turn_on
        entity_id: scene.living_night_guidance_on

  # Spegni la luce notturna quando il movimento in salone è cessato
  - alias: living_motion_night_end
    trigger:
      - platform: state
        entity_id: group.living_motion
        to: 'off'
      - platform: state
        entity_id: binary_sensor.notebook_active
        to: 'off'
    condition:
      condition: and
      conditions:
        # Modalità cinema off
        - condition: state
          entity_id: binary_sensor.cinema_mode
          state: 'off'
        - condition: state
          entity_id: binary_sensor.cinema_paused_mode
          state: 'off'
        # TV spenta (rafforzativo del cinema mode causa instabilità API Philips)
        - condition: state
          entity_id: media_player.tv
          state: 'off'
        # Non mi serve luce utility soggiorno
        - condition: state
          entity_id: input_boolean.need_living_utility_light
          state: 'off'
        # Movimento in salone assente
        - condition: state
          entity_id: group.living_motion
          state: 'off'
        # Notebook spento o idle
        - condition: state
          entity_id: binary_sensor.notebook_active
          state: 'off'
    action:
      - service: scene.turn_on
        entity_id: scene.living_night_guidance_off
