# Entity state scenes and scenarios for bedroom
# FIXME merita una directory dedicata

input_number:

  people_count_bedroom:
    name: 'Persone in camera'
    initial: 0
    min: 0
    # counting known people only for now
    max: 1
    step: 1

automation:

  - alias: bedroom_entering
    id: 8df2842d-dd01-4edf-8723-62eab803f645
    # disabilita finché non abbiamo qualcosa di più affidabile
    initial_state: false
    trigger:
      - trigger: mqtt
        topic: homeassistant/room-trespass/bedroom/direction
        payload: '1'
      # FIXME finché il sensore non sarà affidabile al 100%, per una persona sola va bene
      - trigger: state
        entity_id: group.motion_bedroom
        to: 'on'
    action:
      - action: input_number.increment
        entity_id: input_number.people_count_bedroom
      # Posso affermare che se una persona entra in camera non può essere anche in soggiorno
      - action: input_number.decrement
        entity_id: input_number.people_count_living

  - alias: bedroom_exiting
    id: 7f61584b-cebd-4cb9-aab6-0c2b1624c61b
    # disabilita finché non abbiamo qualcosa di più affidabile
    initial_state: false
    trigger:
      trigger: mqtt
      topic: homeassistant/room-trespass/bedroom/direction
      payload: '2'
    action:
      - action: input_number.decrement
        entity_id: input_number.people_count_bedroom
      # Una persona che esce dalla camera può essere forse in soggiorno.
      # Non affidabile finché non mettiamo un sensore di passaggio nel disimpegno,
      # tuttavia nel frattempo dobbiamo compensare l'azione di bedroom_entering
      - action: input_number.increment
        entity_id: input_number.people_count_living

  - alias: bedroom_enter_light_on
    id: 3f19dfac-8146-4266-b190-629243b56584
    trigger:
      # Presenza in stanza
      - trigger: numeric_state
        entity_id: input_number.people_count_bedroom
        above: '0'
      # Luce naturale scarsa
      # disabilitato - sensore inaffidabile
      #- platform: numeric_state
      #  entity_id: sensor.lux_bedroom
      #  below: !secret bedroom_lux_darkness_threshold
      # Dieci minuti dopo il tramonto
      - trigger: sun
        event: sunset
        offset: "+00:10:00"
    condition:
      condition: and
      conditions:
        # Assicuriamoci che le condizioni del trigger siano tutte rispettate
        - condition: numeric_state
          entity_id: input_number.people_count_bedroom
          above: '0'
        # disabilitato - sensore inaffidabile
        #- condition: numeric_state
        #  entity_id: sensor.lux_bedroom
        #  below: !secret bedroom_lux_darkness_threshold
        - condition: or
          conditions:
            # Da dieci minuti dopo il tramonto...
            - condition: sun
              after: sunset
              after_offset: "+00:10:00"
            # ...fino a mezzora prima dell'alba
            - condition: sun
              before: sunrise
              before_offset: "-00:30:00"
    action:
      # Accendi la luce principale o la luce del letto, a seconda dell'orario
      - action: script.bedroom_turn_on_light_conditional

  - alias: bedroom_exit_light_off
    id: ee46184a-54bf-4293-bcf0-f7f6b6f25b9a
    trigger:
      # Assenza in stanza
      - trigger: numeric_state
        entity_id: input_number.people_count_bedroom
        below: '1'
    action:
      - action: light.turn_off
        entity_id:
          - light.bedroom_main
          - light.bedroom_left

  # Abilita speaker remoto se entra qualcuno in camera
  - alias: bedroom_enter_speaker_on
    id: 928beda3-19c3-4fa1-ab95-641bdb809d44
    trigger:
      # Presenza in stanza
      - trigger: numeric_state
        entity_id: input_number.people_count_bedroom
        above: '0'
    action:
      - action: media_player.volume_mute
        data:
          # FIXME in teoria qui andrebbe messo il gruppo
          entity_id: media_player.snapcast_bedroom
          is_volume_muted: false

  # Muta speaker remoto se escono tutti dalla camera
  - alias: bedroom_exit_speaker_off
    id: 54cb43cb-2365-41fa-8db1-694542aba101
    trigger:
      # Assenza in stanza
      - trigger: numeric_state
        entity_id: input_number.people_count_bedroom
        below: '1'
    action:
      - action: media_player.volume_mute
        data:
          # FIXME in teoria qui andrebbe messo il gruppo
          entity_id: media_player.snapcast_bedroom
          is_volume_muted: true

  # Troppa luce in camera: spegni la luce
  # FIXME sensore inaffidabile
  - alias: bedroom_too_much_light
    id: 3a01afbf-c1b3-46aa-a9e8-b1195c8a9cf8
    trigger:
      - trigger: numeric_state
        entity_id: sensor.lux_bedroom
        # Questa soglia è superabile solo con la luce del sole
        above: !secret bedroom_lux_too_much_threshold
    action:
      - action: light.turn_off
        entity_id:
          - light.bedroom_main
          - light.bedroom_left

  # Attiva luce su movimento contro il muro
  - alias: motion_bedroom_wall
    id: 06c396b8-f9fc-11ef-b763-b4b686ed2aba
    trigger:
      - trigger: state
        # non il gruppo, ci serve il sensore specifico qui
        entity_id: binary_sensor.motion_bedroom_headrest
        to: 'on'
    condition:
      condition: or
      conditions:
        # Da dieci minuti dopo il tramonto...
        - condition: sun
          after: sunset
          after_offset: "+00:10:00"
        # ...fino a mezzora prima dell'alba
        - condition: sun
          before: sunrise
          before_offset: "-00:30:00"
    action:
      # Accendi la luce principale o la luce del letto, a seconda dell'orario
      - action: script.bedroom_turn_on_light_conditional

  - alias: motion_bedroom_day
    id: 7b9e8cf2-31fd-464b-8d9d-4d282686728a
    initial_state: false
    trigger:
      - trigger: state
        entity_id: group.motion_bedroom
        to: 'on'
      - trigger: numeric_state
        entity_id: sensor.lux_bedroom
        below: !secret bedroom_lux_darkness_threshold
    condition:
      condition: and
      conditions:
        # Assicuriamoci che le condizioni del trigger siano tutte rispettate
        - condition: state
          entity_id: group.motion_bedroom
          state: 'on'
        - condition: numeric_state
          entity_id: sensor.lux_bedroom
          below: !secret bedroom_lux_darkness_threshold
    action:
      - action: light.turn_on
        entity_id: light.bedroom_main

  - alias: motion_bedroom_day_ended
    id: 0a2f074e-59aa-414f-ac77-1ef1f31cf3f7
    initial_state: false
    trigger:
      - trigger: state
        entity_id: group.motion_bedroom
        from: 'on'
        to: 'off'
        for: "00:05:00"
    action:
      - action: light.turn_off
        entity_id: light.bedroom_main

  - alias: house_mode_bedroom_night
    id: f4547143-bf58-4414-9a6b-7ba3e8047e72
    trigger:
      - trigger: state
        entity_id: input_select.house_mode
        to: night
    action:
      - action: automation.turn_off
        entity_id:
          #- automation.motion_bedroom_day
          - automation.bedroom_enter_light_on
          - automation.bedroom_exit_light_off

  - alias: house_mode_bedroom_not_night
    id: 6e5ab43c-4b8a-43f4-926f-988db10c618d
    trigger:
      - trigger: state
        entity_id: input_select.house_mode
        from: night
    action:
      - action: automation.turn_on
        entity_id:
          #- automation.motion_bedroom_day
          - automation.bedroom_enter_light_on
          - automation.bedroom_exit_light_off

  - alias: house_mode_bedroom_away
    id: 220e7f4a-a7f3-4093-98a2-7353f028ddaa
    trigger:
      - trigger: state
        entity_id: input_select.house_mode
        to: away
    action:
      # Azzera il conteggio persone (evita falsi positivi)
      - action: input_number.set_value
        data:
          entity_id: input_number.people_count_bedroom
          value: '0'
      - action: media_player.turn_off
        entity_id: media_player.bedroom

  # Spegni la luce principale quando è accesa la luce di sinistra
  - alias: bedroom_turn_off_main_when_left_is_turned_on
    id: fa441766-1c5c-44c0-8234-779dfa7dc8e2
    trigger:
      trigger: state
      entity_id: light.bedroom_left
      to: 'on'
    action:
      - action: light.turn_off
        entity_id: light.bedroom_main

  # Spegni la luce di sinistra quando è accesa la luce principale
  - alias: bedroom_turn_off_left_when_main_is_turned_on
    id: 2ac318b3-d1b7-49b8-8283-57659f15414f
    trigger:
      trigger: state
      entity_id: light.bedroom_main
      to: 'on'
    action:
      - action: light.turn_off
        entity_id: light.bedroom_left

script:

  bedroom_turn_on_light_conditional:
    description: >-
      Accende la luce di sinistra o la luce principale a seconda dell'orario o dell'house mode.
      Se la casa è calma, spegne anche tutte le altre luci.
      Non verifica altre condizioni (tipo la quantità di luce presente).
    sequence:
      - alias: Di notte o in modalità notte
        if:
          - or:
            - condition: time
              after: "23:00:00"
              before: "10:00:00"
            - condition: state
              entity_id: input_select.house_mode
              state: night
        then:
          - action: light.turn_on
            entity_id: light.bedroom_left
          - if:
              - condition: state
                entity_id: binary_sensor.house_night_calm
                state: 'on'
            then:
              - alias: Disabilita luce utility in soggiorno
                action: input_boolean.turn_off
                entity_id: input_boolean.need_living_utility_light
              - alias: Spegni tutte le luci tranne in camera da letto
                action: light.turn_off
                entity_id: light.all_but_bedroom
        else:
          - action: light.turn_on
            entity_id: light.bedroom_main
