# Entity state scenes and scenarios for bedroom

input_number:
  people_count_bedroom:
    name: 'Persone in camera'
    initial: 0
    min: 0
    # counting known people only for now
    max: 1
    step: 1

automation:

  - alias: bedroom_entering
    # disabilita finché non abbiamo qualcosa di più affidabile
    initial_state: off
    trigger:
      - platform: mqtt
        topic: homeassistant/room-trespass/bedroom/direction
        payload: '1'
      # FIXME finché il sensore non sarà affidabile al 100%, per una persona sola va bene
      - platform: state
        entity_id: group.motion_bedroom
        to: 'on'
    action:
      - service: input_number.increment
        entity_id: input_number.people_count_bedroom
      # Posso affermare che se una persona entra in camera non può essere anche in soggiorno
      - service: input_number.decrement
        entity_id: input_number.people_count_living

  - alias: bedroom_exiting
    # disabilita finché non abbiamo qualcosa di più affidabile
    initial_state: off
    trigger:
      platform: mqtt
      topic: homeassistant/room-trespass/bedroom/direction
      payload: '2'
    action:
      - service: input_number.decrement
        entity_id: input_number.people_count_bedroom
      # Una persona che esce dalla camera può essere forse in soggiorno.
      # Non affidabile finché non mettiamo un sensore di passaggio nel disimpegno,
      # tuttavia nel frattempo dobbiamo compensare l'azione di bedroom_entering
      - service: input_number.increment
        entity_id: input_number.people_count_living

  - alias: bedroom_enter_light_on
    trigger:
      # Presenza in stanza
      - platform: numeric_state
        entity_id: input_number.people_count_bedroom
        above: '0'
      # Luce naturale scarsa
      # disabilitato - sensore inaffidabile
      #- platform: numeric_state
      #  entity_id: sensor.bedroom_lux
      #  below: !secret bedroom_lux_darkness_threshold
      # Dieci minuti dopo il tramonto
      - platform: sun
        event: sunset
        offset: "+00:10:00"
    condition:
      condition: and
      conditions:
        # Assicuriamoci che le condizioni del trigger siano tutte rispettate
        - condition: numeric_state
          entity_id: input_number.people_count_bedroom
          above: '0'
        # disabilitato - sensore inaffidabile
        #- condition: numeric_state
        #  entity_id: sensor.bedroom_lux
        #  below: !secret bedroom_lux_darkness_threshold
        - condition: or
          conditions:
            # Da dieci minuti dopo il tramonto...
            - condition: sun
              after: sunset
              after_offset: "+00:10:00"
            # ...fino a mezzora prima dell'alba
            - condition: sun
              before: sunrise
              before_offset: "-00:30:00"
    action:
      # Accendi la luce principale o la luce del letto, a seconda dell'orario
      - service: script.bedroom_turn_on_main_light_conditional
      - service: script.bedroom_turn_on_left_light_conditional

  - alias: bedroom_exit_light_off
    trigger:
      # Assenza in stanza
      - platform: numeric_state
        entity_id: input_number.people_count_bedroom
        below: '1'
    action:
      - service: light.turn_off
        entity_id:
          - light.bedroom_main
          - light.bedroom_left

  # Abilita speaker remoto se entra qualcuno in camera
  - alias: bedroom_enter_speaker_on
    trigger:
      # Presenza in stanza
      - platform: numeric_state
        entity_id: input_number.people_count_bedroom
        above: '0'
    action:
      - service: media_player.volume_mute
        data:
          # FIXME in teoria qui andrebbe messo il gruppo
          entity_id: media_player.snapcast_bedroom
          is_volume_muted: false

  # Muta speaker remoto se escono tutti dalla camera
  - alias: bedroom_exit_speaker_off
    trigger:
      # Assenza in stanza
      - platform: numeric_state
        entity_id: input_number.people_count_bedroom
        below: '1'
    action:
      - service: media_player.volume_mute
        data:
          # FIXME in teoria qui andrebbe messo il gruppo
          entity_id: media_player.snapcast_bedroom
          is_volume_muted: true

  # Troppa luce in camera: spegni la luce
  # FIXME sensore inaffidabile
  - alias: bedroom_too_much_light
    trigger:
      - platform: numeric_state
        entity_id: sensor.bedroom_lux
        # Questa soglia è superabile solo con la luce del sole
        above: !secret bedroom_lux_too_much_threshold
    action:
      - service: light.turn_off
        entity_id:
          - light.bedroom_main
          - light.bedroom_left

  # Attiva luce su movimento contro il muro
  - alias: motion_bedroom_wall
    trigger:
      - platform: state
        # non il gruppo, ci serve il sensore specifico qui
        entity_id: binary_sensor.motion_bedroom
        to: 'on'
    condition:
      condition: or
      conditions:
        # Da dieci minuti dopo il tramonto...
        - condition: sun
          after: sunset
          after_offset: "+00:10:00"
        # ...fino a mezzora prima dell'alba
        - condition: sun
          before: sunrise
          before_offset: "-00:30:00"
    action:
      # Accendi la luce principale o la luce del letto, a seconda dell'orario
      - service: script.bedroom_turn_on_main_light_conditional
      - service: script.bedroom_turn_on_left_light_conditional

  - alias: motion_bedroom_day
    initial_state: off
    trigger:
      - platform: state
        entity_id: group.motion_bedroom
        to: 'on'
      - platform: numeric_state
        entity_id: sensor.bedroom_lux
        below: !secret bedroom_lux_darkness_threshold
    condition:
      condition: and
      conditions:
        # Assicuriamoci che le condizioni del trigger siano tutte rispettate
        - condition: state
          entity_id: group.motion_bedroom
          state: 'on'
        - condition: numeric_state
          entity_id: sensor.bedroom_lux
          below: !secret bedroom_lux_darkness_threshold
    action:
      - service: light.turn_on
        entity_id: light.bedroom_main

  - alias: motion_bedroom_day_ended
    initial_state: off
    trigger:
      - platform: state
        entity_id: group.motion_bedroom
        from: 'on'
        to: 'off'
        for: "00:05:00"
    action:
      - service: light.turn_off
        entity_id: light.bedroom_main

  - alias: house_mode_bedroom_night
    trigger:
      - platform: state
        entity_id: input_select.house_mode
        to: night
    action:
      - service: automation.turn_off
        entity_id:
          #- automation.motion_bedroom_day
          - automation.bedroom_enter_light_on
          - automation.bedroom_exit_light_off

  - alias: house_mode_bedroom_not_night
    trigger:
      - platform: state
        entity_id: input_select.house_mode
        from: night
    action:
      - service: automation.turn_on
        entity_id:
          #- automation.motion_bedroom_day
          - automation.bedroom_enter_light_on
          - automation.bedroom_exit_light_off

  - alias: house_mode_bedroom_away
    trigger:
      - platform: state
        entity_id: input_select.house_mode
        to: away
    action:
      # Azzera il conteggio persone (evita falsi positivi)
      - service: input_number.set_value
        data:
          entity_id: input_number.people_count_bedroom
          value: '0'
      - service: media_player.turn_off
        entity_id: media_player.bedroom

  # Spegni la luce principale quando è accesa la luce di sinistra
  - alias: bedroom_turn_off_main_when_left_is_turned_on
    trigger:
      platform: state
      entity_id: light.bedroom_left
      to: 'on'
    action:
      - service: light.turn_off
        entity_id: light.bedroom_main

  # Spegni la luce di sinistra quando è accesa la luce principale
  - alias: bedroom_turn_off_left_when_main_is_turned_on
    trigger:
      platform: state
      entity_id: light.bedroom_main
      to: 'on'
    action:
      - service: light.turn_off
        entity_id: light.bedroom_left

script:

  # Accende la luce principale prima tra le 10:00 e le 23:00
  # Non verifica altro, richiamata da automation.bedroom_enter_light_on previe opportune verifiche
  bedroom_turn_on_main_light_conditional:
    sequence:
      - condition: template
        value_template: '{{ 10 <= now().hour < 23 }}'
      - service: light.turn_on
        entity_id: light.bedroom_main

  # Accende la luce di sinistra tra le 23:00 e le 10:00
  # Non verifica altro, richiamata da automation.bedroom_enter_light_on previe opportune verifiche
  bedroom_turn_on_left_light_conditional:
    sequence:
      - condition: template
        value_template: '{{ now().hour >= 23 or now().hour < 10 }}'
      - service: light.turn_on
        entity_id: light.bedroom_left
