# House security and alarms
# TODO documentare e assegnare ID

homeassistant:
  customize:
    alarm_control_panel.main:
      friendly_name: Allarme

alarm_control_panel:
  - platform: manual
    name: main
    code: !secret alarm_code
    arming_time: 30
    armed_away:
      delay_time: 15

automation:

  # Rilevato movimento, nessuno in casa ed allarme armato
  - alias: security_trigger_alarm
    trigger:
      # Qualsiasi sensore di movimento scattato
      - trigger: state
        entity_id: group.motion_living
        to: 'on'
      # Porta di ingresso aperta
      - trigger: state
        entity_id: binary_sensor.door_main
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: alarm_control_panel.main
          state: 'armed_away'
    action:
      - action: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.main

  # Tutti usciti, attiva allarme
  - alias: security_autoactivate
    trigger:
      - trigger: numeric_state
        entity_id: sensor.people_count_home
        below: '1'
    action:
      - action: alarm_control_panel.alarm_arm_away
        data:
          entity_id: alarm_control_panel.main
          code: !secret alarm_code

  # Ingresso in casa di persone autorizzate, disattiva allarme
  - alias: security_authorized_entry
    trigger:
      - trigger: numeric_state
        entity_id: sensor.people_count_home
        above: '0'
    action:
      - action: alarm_control_panel.alarm_disarm
        data:
          entity_id: alarm_control_panel.main
          code: !secret alarm_code

  # Movimento rilevato, avvia allarme preliminare
  - alias: security_alarm_pending
    trigger:
      - trigger: state
        entity_id: alarm_control_panel.main
        to: 'pending'
    action:
      - action: media_player.volume_set
        data:
          entity_id: media_player.lounge
          volume_level: 0.05
      - action: media_player.play_media
        data:
          entity_id: media_player.lounge
          media_content_id: !secret security_alarm_warning_media_url
          media_content_type: music
      # Aspetta che lo stato dell'allarme cambi
      - wait_template: "{{ not is_state('alarm_control_panel.main', 'pending') }}"
        timeout: '00:01:00'
      - action: media_player.media_stop
        entity_id: media_player.lounge
      - action: media_player.volume_set
        data:
          entity_id: media_player.lounge
          volume_level: !secret lounge_volume

  - alias: security_alarm_triggered
    trigger:
      - trigger: state
        entity_id: alarm_control_panel.main
        to: 'triggered'
    action:
      - action: script.notify_emergency
        data:
          category: Allarme
          speak: no
          message: |-
            Rilevato movimento in casa!
        # TODO invia fotogramma del movimento e/o link al video
      - action: notify.mobile_app_daniele_shiba
        data:
          message: command_webview
          data:
            command: "/lovelace/security"
            priority: high
            channel: alarm_stream
            tag: security_alarm_triggered

  # Attiva telecamera ingresso su attivazione allarme
  - alias: security_alarm_arming
    trigger:
      - trigger: state
        entity_id: alarm_control_panel.main
        to: 'arming'
    action:
      - action: rest_command.start_living_door_camera

  # Disattiva telecamera ingresso su disattivazione allarme
  - alias: security_alarm_disarmed
    trigger:
      - trigger: state
        entity_id: alarm_control_panel.main
        to: 'disarmed'
    action:
      - action: rest_command.stop_living_door_camera

  # Porta di ingresso aperta per troppo tempo
  - alias: security_door_opened_long_time
    trigger:
      - trigger: state
        entity_id: binary_sensor.door_main
        to: 'on'
        for:
          minutes: 5
    action:
      - action: script.notify_important
        data:
          speak: no
          category: Allarme
          message: |-
            Porta aperta da più di 5 minuti!

  # Notifica attivazione allarme
  - alias: security_alarm_armed
    trigger:
      - trigger: state
        entity_id: alarm_control_panel.main
        to: 'armed_away'
    action:
      - action: rest_command.start_living_door_camera
      - action: script.notify_info
        data:
          category: Allarme
          message: |-
            Allarme armato.

  - alias: security_living_door_camera_disabled
    description: Assicurati che la telecamera di ingresso sia disattiva quando non serve
    id: 64852d3e-eded-11ef-874d-0800277ca3d8
    # casi possibili: avvio HA, restart rasp(motion)
    trigger:
      - trigger: homeassistant
        event: start
      - trigger: state
        entity_id: binary_sensor.living_door_camera_status
        to: 'on'
    condition:
      - condition: state
        entity_id: alarm_control_panel.main
        state: 'disarmed'
    action:
      - action: rest_command.stop_living_door_camera

  - alias: security_living_door_camera_enabled
    description: Assicurati che la telecamera di ingresso sia attiva quando serve
    id: 1d2d5f2f-edee-11ef-b9cd-0800277ca3d8
    trigger:
      - trigger: homeassistant
        event: start
      - trigger: state
        entity_id: binary_sensor.living_door_camera_status
        to: 'off'
    condition:
      - condition: state
        entity_id: alarm_control_panel.main
        state:
          - 'arming'
          - 'armed_away'
          - 'triggered'
    action:
      - action: rest_command.start_living_door_camera
