# House security and alarms

homeassistant:
  customize:
    alarm_control_panel.main:
      friendly_name: Allarme

alarm_control_panel:
  - platform: manual
    name: main
    code: !secret alarm_code
    arming_time: 120
    armed_away:
      delay_time: 60

automation:

  # Rilevato movimento, nessuno in casa ed allarme armato
  - alias: security_trigger_alarm
    trigger:
      # Qualsiasi sensore di movimento scattato
      - platform: state
        entity_id: group.motion_living
        to: 'on'
      # Porta di ingresso aperta
      - platform: state
        entity_id: binary_sensor.door_main
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: alarm_control_panel.main
          state: 'armed_away'
    action:
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.main

  # Tutti usciti, attiva allarme
  - alias: security_autoactivate
    trigger:
      - platform: numeric_state
        entity_id: sensor.people_count_home
        below: '1'
    action:
      - service: alarm_control_panel.alarm_arm_away
        data:
          entity_id: alarm_control_panel.main
          code: !secret alarm_code

  # Ingresso in casa di persone autorizzate, disattiva allarme
  - alias: security_authorized_entry
    trigger:
      - platform: numeric_state
        entity_id: sensor.people_count_home
        above: '0'
    action:
      - service: alarm_control_panel.alarm_disarm
        data:
          entity_id: alarm_control_panel.main
          code: !secret alarm_code

  # Movimento rilevato, avvia allarme preliminare
  - alias: security_alarm_pending
    trigger:
      - platform: state
        entity_id: alarm_control_panel.main
        to: 'pending'
    action:
      - service: media_player.volume_set
        data:
          entity_id: media_player.lounge
          volume_level: 0.05
      - service: media_player.play_media
        data_template:
          entity_id: media_player.lounge
          media_content_id: !secret security_alarm_warning_media_url
          media_content_type: music
      # Aspetta che lo stato dell'allarme cambi
      - wait_template: "{{ not is_state('alarm_control_panel.main', 'pending') }}"
        timeout: '00:01:00'
      - service: media_player.media_stop
        entity_id: media_player.lounge
      - service: media_player.volume_set
        data:
          entity_id: media_player.lounge
          volume_level: !secret lounge_volume

  - alias: security_alarm_triggered
    trigger:
      - platform: state
        entity_id: alarm_control_panel.main
        to: 'triggered'
    action:
      - service: notify.kontalk_daniele
        data_template:
          title: "Allarme"
          message: |-
            Rilevato movimento in casa!
        # TODO invia fotogramma del movimento e/o link al video

  # Attiva telecamera ingresso su attivazione allarme
  - alias: security_alarm_arming
    trigger:
      - platform: state
        entity_id: alarm_control_panel.main
        to: 'arming'
    action:
      - service: shell_command.start_living_door_camera

  # Disattiva telecamera ingresso su disattivazione allarme
  - alias: security_alarm_disarmed
    trigger:
      - platform: state
        entity_id: alarm_control_panel.main
        to: 'disarmed'
    action:
      - service: shell_command.stop_living_door_camera

  # Porta di ingresso aperta per troppo tempo
  - alias: security_door_opened_long_time
    trigger:
      - platform: state
        entity_id: binary_sensor.door_main
        to: 'on'
        for:
          minutes: 5
    action:
      - service: notify.kontalk_daniele
        data_template:
          title: "Allarme"
          message: |-
            porta aperta da più di 5 minuti!

  # Notifica attivazione allarme
  - alias: security_alarm_armed
    trigger:
      - platform: state
        entity_id: alarm_control_panel.main
        to: 'armed_away'
    action:
      - service: shell_command.start_living_door_camera
      - service: notify.kontalk_daniele
        data_template:
          title: "Allarme"
          message: |-
            armato.
