homeassistant:
  customize:
    zone.home:
      friendly_name: Casa

    zone.work:
      friendly_name: Lavoro

zone:
  - name: Home
    latitude: !secret latitude_home
    longitude: !secret longitude_home
    radius: 20
    icon: mdi:home

  - name: Work
    latitude: !secret latitude_work
    longitude: !secret longitude_work
    radius: 300
    icon: mdi:worker
