# HASS core (scatola)

homeassistant:
  customize:
    binary_sensor.internet:
      friendly_name: Internet
      icon: mdi:web

command_line:
  - sensor:
      name: ac_status_scatola
      command: 'cat /sys/class/power_supply/AC/online'
  - sensor:
      name: cputemp_scatola
      command: '/usr/bin/sensors -j'
      value_template: '{{ value_json["coretemp-isa-0000"]["Package id 0"]["temp1_input"] }}'
      unit_of_measurement: '°C'

sensor:
  # FIXME il kernel non rileva più la batteria -.-
  - platform: linux_battery
    name: battery_scatola
    battery: 0

binary_sensor:
  - platform: template
    sensors:
      battery_discharging_scatola:
        friendly_name: "Batteria scatola in scaricamento"
        value_template: "{{ states.sensor.ac_status_scatola.state == '0' }}"

automation:

  - alias: scatola_on_fire
    trigger:
      - trigger: numeric_state
        entity_id: sensor.cputemp_scatola
        above: 73
        for:
          minutes: 10
    action:
      action: script.notify_important
      data:
        category: Sistema
        speak: no
        message: |-
          Temperatura scatola eccessiva: {{ states.sensor.cputemp_scatola.state_with_unit }}

  - alias: speedtest
    trigger:
      trigger: time_pattern
      hours: "/3"
    action:
      action: homeassistant.update_entity
      target:
        entity_id: sensor.speedtest_ping
