# HASS core (scatola)

homeassistant:
  customize:
    sensor.battery_core:
      friendly_name: Scatola
    device_tracker.internet:
      friendly_name: Internet

sensor:
  - platform: linux_battery
    name: battery_core
    battery: 0

  - platform: command_line
    name: ac_status_core
    command: 'cat /sys/class/power_supply/AC/online'

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: processor_use

  - platform: command_line
    name: core_temperature
    command: '/usr/bin/sensors -j'
    value_template: '{{ value_json["coretemp-isa-0000"]["Package id 0"]["temp1_input"] }}'
    unit_of_measurement: '°C'

binary_sensor:
  - platform: template
    sensors:
      core_battery_discharging:
        friendly_name: "Batteria core in scaricamento"
        value_template: "{{ states.sensor.ac_status_core.state == '0' }}"

device_tracker:
  - platform: ping
    hosts:
      internet: 8.8.8.8
    count: 2
    interval_seconds: 30
    consider_home: 0

automation:

  - alias: core_on_fire
    trigger:
      - platform: numeric_state
        entity_id: sensor.core_temperature
        above: 70
        for:
          minutes: 10
    action:
      service: notify.kontalk_daniele
      data_template:
        title: "Allarme"
        message: |-
          Temperatura core eccessiva: {{ states.sensor.core_temperature.state_with_unit }}
