# Media Center Raspberry

homeassistant:
  customize:
    # FIXME generato da integrazione, dovremmo cambiarla?
    sensor.mediarasp_cpu_thermal_1_temperature:
      friendly_name: Temperatura CPU Media Rasp
    sensor.uptime_mediarasp:
      friendly_name: Uptime
    automation.media_rasp_on_fire:
      friendly_name: Media Rasp calda

sensor:

  # Unsupported by Glances integration
  - platform: rest
    resource: http://rasp:61208/api/4/uptime
    name: uptime_mediarasp
    value_template: '{{ value_json }}'
    scan_interval: 300

automation:

  - alias: media_rasp_on_fire
    trigger:
      - platform: numeric_state
        entity_id: sensor.mediarasp_cpu_thermal_1_temperature
        above: 75
        for:
          minutes: 15
    action:
      service: script.notify_important
      data:
        category: Sistema
        speak: no
        message: |-
          Temperatura media rasp eccessiva: {{ states.sensor.mediarasp_cpu_thermal_1_temperature.state_with_unit }}
