# Domotics Network management

# TODO probabilmente è sufficiente la domonet_interface; external_interface è ridondante
# cerchiamo di usare più gli IP in generale
shell_command:
  domonet_device_allow_internet: >-
    sudo bin/domonet_allow.sh {{ domonet_interface }} {{ external_interface }} {{ host_address }} "{{ host_description }}"
  domonet_device_disallow_internet: >-
    sudo bin/domonet_disallow.sh {{ host_address }}
  domonet_global_allow_internet: >-
    sudo bin/domonet_allow.sh {{ domonet_interface }} {{ external_interface }} 0.0.0.0/0 "(all devices)"
  domonet_global_disallow_internet: >-
    sudo bin/domonet_disallow_global.sh {{ domonet_interface }} {{ external_interface }} "(all devices)"

script:

  domonet_device_enable_internet:
    description: "Enable Internet access for a Domonet device"
    fields:
      host_address:
        description: "Device address"
        example: "192.168.100.220"
      host_description:
        description: "Device description (it will be added as iptables rule comment)"
        example: "Google Home"
    mode: queued
    sequence:
      - action: shell_command.domonet_device_allow_internet
        data:
          domonet_interface: !secret domonet_interface
          external_interface: !secret external_interface
          host_address: "{{ host_address }}"
          host_description: "{{ host_description }}"

  domonet_autodevice_toggle_internet:
    description: "Toggle Internet access for a Domonet (automatic) device"
    fields:
      entity_id:
        description: "Domonet client entity id"
        example: "binary_sensor.domonet_allowed_googlehome"
    mode: queued
    sequence:
      - choose:
        - conditions: "{{ is_state(entity_id, 'on') }}"
          sequence:
            - action: shell_command.domonet_device_disallow_internet
              data:
                host_address: "{{ states[entity_id].attributes['device_address'] }}"
        default:
          - action: shell_command.domonet_device_allow_internet
            data:
              domonet_interface: !secret domonet_interface
              external_interface: !secret external_interface
              host_address: "{{ states[entity_id].attributes['device_address'] }}"
              host_description: "{{ states[entity_id].attributes['device_name'] }}"
      - alias: Update status of domonet devices
        event: domonet_update
        event_data:
          device_name: "{{ states[entity_id].attributes['device_name'] }}"
          device_address: "{{ states[entity_id].attributes['device_address'] }}"

  domonet_device_disable_internet:
    description: "Disable Internet access for a Domonet device"
    fields:
      host_address:
        description: "Device address"
        example: "192.168.100.220"
    mode: queued
    sequence:
      - action: shell_command.domonet_device_disallow_internet
        data:
          host_address: "{{ host_address }}"

  domonet_all_enable_internet:
    description: "Enable Internet access for all Domonet devices"
    mode: queued
    sequence:
      - action: shell_command.domonet_global_allow_internet
        data:
          domonet_interface: !secret domonet_interface
          external_interface: !secret external_interface
      - action: homeassistant.update_entity
        entity_id: binary_sensor.domonet_allowed_global

  domonet_all_disable_internet:
    description: "Disable Internet access for all Domonet devices"
    mode: queued
    sequence:
      - action: shell_command.domonet_global_disallow_internet
        data:
          domonet_interface: !secret domonet_interface
          external_interface: !secret external_interface
      - action: homeassistant.update_entity
        entity_id: binary_sensor.domonet_allowed_global

command_line:
  - sensor:
      name: domonet_devices
      command: bin/domonet_clients.sh {{ states.sensor.domonet_interface.state }}
      scan_interval: 15
      value_template: "{{ value_json.clients | length }}"
      json_attributes:
        - clients

  - binary_sensor:
      name: domonet_allowed_global
      scan_interval: 60
      command: sudo bin/domonet_check_global.sh {{ states.sensor.domonet_interface.state }} {{ states.sensor.external_interface.state }} "(all devices)"
      payload_on: "1"
      payload_off: "0"

sensor:

  - platform: template
    sensors:
      domonet_interface:
        value_template: !secret domonet_interface
      external_interface:
        value_template: !secret external_interface
