# Media Center Raspberry

homeassistant:
  customize:
    sensor.mediarasp_cpu_thermal_1_temp:
      friendly_name: Temperatura CPU Media Rasp
    sensor.mediarasp_uptime:
      friendly_name: Uptime
    automation.media_rasp_on_fire:
      friendly_name: Media Rasp calda

glances:

  - host: rasp
    name: mediarasp
    version: 3

sensor:

  # Unsupported by Glances integration
  - platform: rest
    resource: http://rasp:61208/api/3/uptime
    name: mediarasp_uptime
    value_template: '{{ value_json }}'
    scan_interval: 300

automation:

  - alias: media_rasp_on_fire
    trigger:
      - platform: numeric_state
        entity_id: sensor.mediarasp_cpu_thermal_1_temp
        above: 75
        for:
          minutes: 15
    action:
      service: notify.kontalk_daniele
      data_template:
        title: "Allarme"
        message: |-
          Temperatura media rasp eccessiva: {{ states.sensor.mediarasp_cpu_thermal_1_temp.state_with_unit }}
