# Home server monitoring

homeassistant:
  customize:
    sensor.homeserver_package_id_0_temperature:
      friendly_name: Temperatura CPU server
    sensor.hddtemp_homeserver_dev_disk_by_id_ata_wdc_wd1002faex_00z3a0_wd_wcatr9149732:
      friendly_name: Dati 1
    sensor.hddtemp_homeserver_dev_disk_by_id_ata_wdc_wd1002faex_00z3a0_wd_wcatr9159143:
      friendly_name: Dati 2
    sensor.hddtemp_homeserver_dev_disk_by_id_ata_wdc_wds500g1r0a_68a4w0_214513802580:
      friendly_name: Sistema 1
    sensor.hddtemp_homeserver_dev_disk_by_id_ata_wdc_wds500g1r0a_68a4w0_214513802589:
      friendly_name: Sistema 2
    sensor.uptime_homeserver:
      friendly_name: Uptime
    automation.server_on_fire:
      friendly_name: Server caldo

sensor:

  - platform: hddtemp
    name: hddtemp_homeserver
    host: server
    disks:
      - /dev/disk/by-id/ata-WDC_WD1002FAEX-00Z3A0_WD-WCATR9149732
      - /dev/disk/by-id/ata-WDC_WD1002FAEX-00Z3A0_WD-WCATR9159143
      - /dev/disk/by-id/ata-WDC_WDS500G1R0A-68A4W0_214513802580
      - /dev/disk/by-id/ata-WDC_WDS500G1R0A-68A4W0_214513802589

  # Unsupported by Glances integration
  - platform: rest
    resource: http://server:61208/api/4/uptime
    name: uptime_homeserver
    value_template: '{{ value_json }}'
    scan_interval: 300

automation:

  - alias: server_on_fire
    trigger:
      - platform: numeric_state
        entity_id: sensor.hddtemp_homeserver_dev_disk_by_id_ata_wdc_wd1002faex_00z3a0_wd_wcatr9149732
        above: 51
        for:
          minutes: 10
      - platform: numeric_state
        entity_id: sensor.hddtemp_homeserver_dev_disk_by_id_ata_wdc_wd1002faex_00z3a0_wd_wcatr9159143
        above: 51
        for:
          minutes: 10
      - platform: numeric_state
        entity_id: sensor.homeserver_package_id_0_temperature
        above: 54
        for:
          minutes: 10
    action:
      service: script.notify_important
      data:
        category: Sistema
        speak: no
        message: |-
          Temperatura server eccessiva!
          Core: {{ states.sensor.homeserver_package_id_0_temperature.state_with_unit }}
          Disco 1: {{ states.sensor.hddtemp_homeserver_dev_disk_by_id_ata_wdc_wd1002faex_00z3a0_wd_wcatr9149732.state_with_unit }}
          Disco 2: {{ states.sensor.hddtemp_homeserver_dev_disk_by_id_ata_wdc_wd1002faex_00z3a0_wd_wcatr9159143.state_with_unit }}

  - alias: house_mode_system_homeserver_day
    trigger:
      - platform: state
        entity_id: input_select.house_mode
        to: day_working
      - platform: state
        entity_id: input_select.house_mode
        to: day_not_working
    action:
      - service: switch.turn_on
        entity_id: switch.homeserver

  - alias: house_mode_system_homeserver_night
    trigger:
      - platform: state
        entity_id: input_select.house_mode
        to: night
    action:
      - service: switch.turn_off
        entity_id: switch.homeserver

switch:
  - platform: wake_on_lan
    name: homeserver
    host: server
    mac: !secret homeserver_mac_address
    turn_off:
      service: shell_command.homeserver_suspend

shell_command:
  homeserver_suspend: ssh homeassistant@server sudo systemctl suspend
  homeserver_reboot: ssh homeassistant@server sudo systemctl reboot
  homeserver_poweroff: ssh homeassistant@server sudo systemctl poweroff
